### ISSUE TITLE
Unresolved reference: datetime [Multiplatform]

### ISSUE THREAD

**Issue by SchweinchenFuntik** [Kotlin/kotlinx-datetime#105]
Multi-module project structure, where there is a common module that is multi-platform

common `build.gradle.kts`
```kotlin
plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
}

group = "group"
version = "1.0.0-SNAPSHOT"

kotlin {
    jvm {
        compilations.all {
            kotlinOptions.jvmTarget = "11"
        }
        testRuns["test"].executionTask.configure {
            useJUnit()
        }
    }
    js(BOTH) {
        browser {
            testTask {
                useKarma {
                    useChromeHeadless()
                    webpackConfig.cssSupport.enabled = true
                }
            }
        }
    }
    val hostOs = System.getProperty("os.name")
    val isMingwX64 = hostOs.startsWith("Windows")
    val nativeTarget = when {
        hostOs == "Mac OS X" -> macosX64("native")
        hostOs == "Linux" -> linuxX64("native")
        isMingwX64 -> mingwX64("native")
        else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
    }
    
    sourceSets {
        val commonMain by getting {
            dependencies {
                api("org.jetbrains.kotlinx:kotlinx-datetime:0.1.1")
                api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.1.0")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
        val jvmMain by getting
        val jvmTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
            }
        }
        val jsMain by getting
        val jsTest by getting {
            dependencies {
                implementation(kotlin("test-js"))
            }
        }
        val nativeMain by getting
        val nativeTest by getting
    }
}

```

common module
![изображение](https://user-images.githubusercontent.com/22637705/112816374-034a0000-908a-11eb-9bc5-4d55b16ec2ab.png)

jvm module
![изображение](https://user-images.githubusercontent.com/22637705/112816016-99c9f180-9089-11eb-9532-8e84dfe2af00.png)

js module
![изображение](https://user-images.githubusercontent.com/22637705/112816228-da296f80-9089-11eb-8524-a25deac0c604.png)

native module
![изображение](https://user-images.githubusercontent.com/22637705/112816300-edd4d600-9089-11eb-9ef9-46bffcfad2d9.png)

**Comment by dkhalanskyjb** [comment]
Does the problem only occur in the IDE or does this also affect building the project? Also, which operating system are you on?

**Comment by SchweinchenFuntik** [comment]
OS: Ubuntu 20.04
similar issue with kotlinx-serialization-json.
build successful 
```kotlin
import kotlinx.datetime.Clock


fun t2(): Clock = TODO()
```

**Comment by dkhalanskyjb** [comment]
I attempted to make a small project with your build script on Arch Linux and couldn't reproduce this problem with IDEA Community Edition 2020.3. Could you download my project from https://drive.google.com/file/d/1nSLFZHNz5FWwIGHGZqXgvGCVsGp_mICS/view?usp=sharing and check whether the problem occurs there as well?

Regardless, given that the build proceeds fine, it looks like the problem is with the IDE, not with the library itself (especially since another library exhibits the same behavior). Actions that sometimes help in such cases:
* Reimport the Gradle project.
* Run the Gradle `clean` and `build` actions from the IDE itself.
* File → Invalidate Caches/Restart → Invalidate and Restart.

**Comment by SchweinchenFuntik** [comment]
same.  Invalidate Caches/Restart, clean-build - performed
![изображение](https://user-images.githubusercontent.com/22637705/112838577-de638600-90a5-11eb-99d3-60524003d2a2.png)

**Comment by SchweinchenFuntik** [comment]
I will report to YouTrack

**Comment by SchweinchenFuntik** [comment]
deleted all configs and caches, reinstalled IDEA
