### ISSUE TITLE
Make compatible with Kotlin 1.5

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlinx-datetime#108]
The versions 0.1.0 and 0.1.1 are incompatible with Kotlin 1.5.0 due to the changes in the experimental `Duration` inline value class there, which is widely used in `kotlinx-datetime`.

When using these versions with Kotlin 1.5, users can observe the following stack traces:
```
kotlin.time.DurationKt.getNanoseconds(J)D
java.lang.NoSuchMethodError: kotlin.time.DurationKt.getNanoseconds(J)D
	at kotlinx.datetime.DateTimeUnit$TimeBased.<init>(DateTimeUnit.kt:54)
	at kotlinx.datetime.DateTimeUnit.<clinit>(DateTimeUnit.kt:108)
```
or
```
java.lang.NoSuchMethodError: ‘kotlinx.datetime.Instant kotlinx.datetime.Instant.plus-LRDsOJo(long)’
```

**Comment by ilya-g** [comment]
If anyone wants to try a preliminary version of `kotlinx-datetime` for Kotlin 1.5, it can be found in this maven repository `https://teamcity.jetbrains.com/guestAuth/app/rest/builds/buildType:(KotlinTools_KotlinxDatetime_Build_All),status:success,branch:kotlin-1-5,pinned:true/artifacts/content/maven/` 
under the coordinates 
`org.jetbrains.kotlinx:kotlinx-datetime:0.2.0-dev-303`

**Comment by only-kuban** [comment]
@ilya-g Link not work. Please add link in maven repository. Or writen guide for install 0.2.0 kotlinx-datetime for kotlin 1.5. Please.

**Comment by hfhbd** [comment]
@only-kuban The link does not work from your browser, but with Gradle.

```kotlin
// build.gradle.kts
repositories {
    maven(url = "https://teamcity.jetbrains.com/guestAuth/app/rest/builds/buildType:(KotlinTools_KotlinxDatetime_Build_All),status:success,branch:kotlin-1-5,pinned:true/artifacts/content/maven/")
}
dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.2.0-dev-303")
}

**Comment by only-kuban** [comment]
![image](https://user-images.githubusercontent.com/20380330/115406264-ae685800-a1f7-11eb-88f4-36d710ce46e1.png)
Not work gradle task for iosTest. Help please. Screenshot added.

**Comment by dkhalanskyjb** [comment]
@only-kuban could you show the actual error that you're getting? Your screenshot doesn't include the error, just some debug info.

**Comment by only-kuban** [comment]
@dkhalanskyjb yes, add screenshot
![image](https://user-images.githubusercontent.com/20380330/115407964-24b98a00-a1f9-11eb-847f-0096368c321e.png)

**Comment by dkhalanskyjb** [comment]
Thanks, @only-kuban! I was able to reproduce a problem, which could be the same as what you're experiencing. I'll `@`-mention you when we fix it.

**Comment by dkhalanskyjb** [comment]
There's now a new preview version:
* Repository: https://teamcity.jetbrains.com/guestAuth/repository/download/KotlinTools_KotlinxDatetime_Build_All/3436908:id/maven/
* Artifact: `org.jetbrains.kotlinx:kotlinx-datetime:0.2.0-dev-310`

Example:
```gradle
repositories {
    maven(url = "https://teamcity.jetbrains.com/guestAuth/repository/download/KotlinTools_KotlinxDatetime_Build_All/3436908:id/maven/")
}
dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.2.0-dev-310")
}
```

@only-kuban could you please check it out?

**Comment by only-kuban** [comment]
@dkhalanskyjb after insert repo in build.gradle.kts and load gradle changes i have error in screenshot
![image](https://user-images.githubusercontent.com/20380330/115863946-dd243f80-a43e-11eb-9226-f2e1a35d8063.png)

**Comment by ilya-g** [comment]
The version 0.2.0 compatible with Kotlin 1.5 is available in maven central. Please update your dependencies if you used test builds from teamcity, as they will be cleaned up soon.

**Comment by only-kuban** [comment]
Thanks, it's worked!
