### ISSUE TITLE
Issue with 8601 parsing

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [Kotlin/kotlinx-datetime#115]
Hey all 👋 I think there was an ISO 8601 compliant format that was missed with the latest batch of serializers for `LocalDateTime`. To my understanding, `2021-01-27T01:48:31.585Z` should be considered a valid ISO-8601 date, however, attempting to parse this using this library results in the following

```
Exception in thread "main" kotlinx.datetime.DateTimeFormatException: java.time.format.DateTimeParseException: Text '2021-01-27T01:48:31.585Z' could not be parsed, unparsed text found at index 23
	at kotlinx.datetime
```

Easy enough to reproduce, basically this exact string _should_ be parseable by the serializations 😃

**Comment by dkhalanskyjb** [comment]
Hi! This string can be parsed as an `Instant`, not as `LocalDateTime`. `LocalDateTime` represents clock readings, whereas `2021-01-27T01:48:31.585Z` is an absolute moment in time.

Solutions:
* `Instant.parse(string).toLocalDateTime(TimeZone.UTC)`
* Remove `Z` from the end of the string, then `LocalDateTime.parse` will work.

**Comment by rgbrizzlehizzle** [comment]
![doh](https://user-images.githubusercontent.com/5607577/118395360-fa9c9180-b617-11eb-98bf-de50dcc0651b.gif)

Me when I forget about `Instant` 😄  

Thanks!!
