### ISSUE TITLE
uses wrong name for kotlinx-serialization module with legacy compiler

### ISSUE THREAD

**Issue by ethanmdavidson** [Kotlin/kotlinx-datetime#118]
repo demonstrating issue: https://github.com/ethanmdavidson/serializationNameBug

When using the legacy compiler, kotlinx-datetime uses an old name when referencing kotlinx-serialization: 'kotlinx-serialization-kotlinx-serialization-core-jsLegacy' instead of 'kotlinx-serialization-kotlinx-serialization-core-js-legacy'.

May be related to https://youtrack.jetbrains.com/issue/KT-46598

I think it might be fixed by simply upgrading kotlinx.serialization to 1.2.1 (latest version)

**Comment by dkhalanskyjb** [comment]
Thanks for raising this, your reproducer is great! Yes, either rebuilding the datetime library with dependency on `kotlinx.serialization` 1.2.1 or using `kotlinx.serialization` 1.1.0 does fix the issue. This problem is unexpected, we will be looking into it.

**Comment by set321go** [comment]
It looks like this is the cause https://youtrack.jetbrains.com/issue/KT-43237 so my interpretation is everything that there is now an incompatability between modules published with 1.4 and 1.5
