### ISSUE TITLE
Exceptions when using availableZoneIds

### ISSUE THREAD

**Issue by kevindmoore** [Kotlin/kotlinx-datetime#127]
When using TimeZone.availableZoneIds, I see the following exceptions. (I still get the values though):
Rejecting re-init on previously-failed class java.lang.Class<kotlinx.datetime.serializers.TimeZoneSerializer>: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/serialization/KSerializer;
2021-06-05 14:19:44.679 7988-7988/com.raywenderlich.timezone.android I/imezone.androi:     at void kotlinx.datetime.TimeZone.<clinit>() (TimeZoneJvm.kt:-1)

I am using:
    kotlin("plugin.serialization") version "1.5.0"

with Jetpack Compose and Multiplatform

**Comment by dkhalanskyjb** [comment]
I tried to reproduce this in https://github.com/dkhalanskyjb/AndroidSandbox (without using the serialization compiler plugin, Jetpack Compose, and multiplatform, as I hope that they are not relevant), but, judging by the output of `logcat`, nothing interesting happened.

Maybe you have a small, self-contained project where the problem is present? It would be of great help.

**Comment by kevindmoore** [comment]
So, I am using the Serialization plugin and I suspect that that is the
issue as the logcat mentions serialization.
Thanks,
Kevin Moore

**Comment by dkhalanskyjb** [comment]
The reason why I think that the plugin is irrelevant is that the plugin is needed to process annotations—to generate serializers, set the default serializers, etc. This issue looks like a problem with simply accessing an existing serializer (and it's unclear why it is accessed).

In any case, I double-checked and attempted to also use the serialization plugin: https://github.com/dkhalanskyjb/AndroidSandbox/commit/b2d9d739549cc49ea9be4d1eb4aaa5419c5620a2 Doesn't look like it's made a difference.

**Comment by dkhalanskyjb** [comment]
Hi @kevindmoore! Do you have any news about the issue?

**Comment by kevindmoore** [comment]
I've just removed the serialization plugin as I don't need it now.

**Comment by dkhalanskyjb** [comment]
Well, given that we couldn't reproduce this and no one else reported anything similar, let's just hope this strange event just went away on its own.
