### ISSUE TITLE
How to convert string in format "yyyy-mm-dd hh:mm:ss" to localDateTime?

### ISSUE THREAD

**Issue by ccc-sseylani** [Kotlin/kotlinx-datetime#128]
I am getting a date in a format like this "2021-03-26 22:02:53"  from the API which is not ISO format, and I created a custom serializer for it but I am getting an error.
I also do not want to use ISO format, and I want to send back the date as "yyyy-mm-dd hh:mm:ss".

Since We can not use Java.Date in Kotlin multiplatform, what is the proper solution to serialize date format like this? 

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/75082292/121060577-d5232380-c790-11eb-87ab-d3c10dce54b8.png">

<img width="807" alt="image" src="https://user-images.githubusercontent.com/75082292/121060612-e2d8a900-c790-11eb-95ca-9ab846d3cead.png">

Thanks

**Comment by dkhalanskyjb** [comment]
Sorry, we don't have such functionality currently. There are many requests for it though (https://github.com/Kotlin/kotlinx-datetime/labels/formatters), so we are thinking about this.

**Comment by ilya-g** [comment]
The format looks very similar to the ISO format of LocalDateTime, except that the date and time components are separated with a space instead of `T`. So as a workaround, you can replace `' '` with `'T'` and use `LocalDateTime.parse` to parse the result:
```
LocalDateTime.parse("2021-03-26 22:02:53".replaceFirst(' ', 'T')
```

**Comment by galipkaya** [comment]
Can this issue be solved by giving an optional format string parameter to `LocalDateTime.parse` and using this format parameter in type `DateTimeFormatter. ofPattern`?

**Comment by DenisGithuku** [comment]
You can actually use the date time formatter to parse the string then use the local date to parse into your requirements 
`            val formatter =DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") 
             val formattedDate = LocalDate.parse(date, formatter)`

**Comment by dkhalanskyjb** [comment]
Except that's Java.
