### ISSUE TITLE
Jalali Data System

### ISSUE THREAD

**Issue by ali77gh** [Kotlin/kotlinx-datetime#138]
Hi.
This library supports Gregorian Date System. but there is some other date systems in the world.
one of them is [Persian Solar Hijri](https://www.timeanddate.com/calendar/persian-calendar.html) that also knows as [Jalali](https://en.wikipedia.org/wiki/Jalali_calendar) and used in many countries as main date system.
i'm able to add this system to this library (I done same thing before [here](https://github.com/hooshkar/AndroidMultiCalendarTools)).
I'm not gonna touch current functionality (just add some functions to convert to jalali).
If you are interested , just let me know. It will be done in few weeks.
so...
What do you think?

**Comment by elizarov** [comment]
This library is currently focused on supporting [ISO 8601 international standard](https://en.wikipedia.org/wiki/ISO_8601). We don't plan to expand it beyond ISO 8601 in the near future.
