### ISSUE TITLE
kmm Instant conversion to NSDate

### ISSUE THREAD

**Issue by alednik** [Kotlin/kotlinx-datetime#140]
Trying to convert `Instant` to `NSDate`. I have got incorrect `NSDate` (year converts incorrectly), instead of 2021 it converts to 2052, but day and month are correct. Used convertter https://github.com/Kotlin/kotlinx-datetime/blob/3af71d2e874592fc70282de441a09d024dcefb54/core/darwin/src/Converters.kt.
Can anyone help to solve this problem or advice some workaround?

**Comment by dkhalanskyjb** [comment]
Hi! Sorry, I couldn't reproduce this.
```kotlin
    fun issue140() {
        val systemTZ = TimeZone.currentSystemDefault()
        val now = Clock.System.now()
        val curDayIndex = now.toLocalDateTime(systemTZ).dayOfWeek.isoDayNumber - 1
        val i = now.minus(curDayIndex, DateTimeUnit.DAY, systemTZ)
        val nsdate = i.toNSDate()
        println("$systemTZ $now $curDayIndex $i $nsdate")
    }
```
This code produces the following for me:
```
Europe/Moscow 2021-09-01T08:27:32.722Z 2 2021-08-30T08:27:32.722Z 2021-08-30 08:27:32 +0000
```
Does this snippet, too, produce the wrong result on your machine?

**Comment by alednik** [comment]
Hi! Thanks a lot for your efforts!
Unfortunately, on my machine there is following result
`Europe/Minsk 2021-09-01T14:48:22.647Z 2 2021-08-30T14:48:22.647Z 2052-08-30 14:48:22 +0000` 
The same result also on real device

**Comment by dkhalanskyjb** [comment]
Oh.
What about this code?
```kotlin
        val instant = Instant.parse("2021-08-30T14:48:22.647Z")
        println(instant.epochSeconds)
        val seconds = instant.epochSeconds.toDouble()
        println(seconds)
        val nsdate1 = NSDate.dateWithTimeIntervalSince1970(seconds)
        println(nsdate1)
        val nsdate2 = instant.toNSDate()
        println(nsdate2)
```
Also, what is the return value of
```swift
NSDate.init(timeIntervalSince1970: 1630334902)
```
in the Swift console?

**Comment by alednik** [comment]
Hi!
Sorry for the delay
First snippet output:
```
1630334902
1.630334902E9
2021-08-30 14:48:22 +0000
2052-08-30 14:48:22 +0000
```
Second snippet output:
```
2021-08-30 14:48:22 +0000
```

**Comment by dkhalanskyjb** [comment]
Glad you're here, this issue really intrigues me!
I made a small self-contained project on which I observe no issues. Could you please clone the project https://github.com/dkhalanskyjb/toNsDateBug and run `src/iosTest/kotlin/me/user/library/iosTest.kt` from there?

**Comment by alednik** [comment]
Hi!
Test passed. Console output from the test
```
instant: 2021-09-15T18:36:48.489Z
epoch seconds: 1631731008
nsdate: 2021-09-15 18:36:48 +0000
nsdate epoch seconds: 1.631731008489E9
```

**Comment by dkhalanskyjb** [comment]
`toNSDate` worked here, it seems. This means that the issue must lie in something inside your specific project, not with your machines or our implementation in general. There's not much we can do unless you provide some (preferably small) project where this issue occurs.

**Comment by dkhalanskyjb** [comment]
Hi @alednik! Any news on this?
