### ISSUE TITLE
Question: usage in mixed Java / Kotlin project

### ISSUE THREAD

**Issue by AlexTrotsenko** [Kotlin/kotlinx-datetime#160]
Was `kotlinx-datetime` designed to be used in _mixed_ Java/Kotlin projects in terms of public api, which are exposed to Java?
Or should `java.time` be preferred options for such cases?

**Comment by dkhalanskyjb** [comment]
Kotlin is in general easy to use along with Java, including calling Kotlin code from Java. So, while we did not *design* this library in particular for your use case, there should be no issues nonetheless. We do use extension functions heavily though, which don't look as pretty when called from Java.

**Comment by ilya-g** [comment]
Some methods operate with Kotlin `Duration` class which is an inline value class. That makes it impossible to call them from Java code, because their names are mangled.

**Comment by AlexTrotsenko** [comment]
@dkhalanskyjb , @ilya-g  thanks for your feedback and pointing out problematic cases as well as confirming, that interoperability with Java platform was not part of the intentional design. 

Given everything mentioned above, I believe for the such `mixed`/`legacy` project only `JSR 310` is the reliable way to go.

**Comment by AlexTrotsenko** [comment]
@dkhalanskyjb  one more follow-up question - I have noticed, that for `Native` target it's also not recommended to use `kotlinx-datetime` directly: https://github.com/Kotlin/kotlinx-datetime/issues/78#issuecomment-740573900.

I am wondered if you think that it worth to mention somewhere in the README that `kotlinx-datetime` are not designed to be used from the platform code ? 
E.g. in the [Implementation](https://github.com/Kotlin/kotlinx-datetime#implementation) section or perhaps in the separate _"Platforms interoperability"_ section? Perhaps there you can also point out usage of converters, etc. ?

**Comment by dkhalanskyjb** [comment]
`kotlinx-datetime` doesn't really do anything special in regards to platform compatibility: it's just a mostly-pure-Kotlin library designed to be a good Kotlin library. The caveats with platform compatibility are exactly the same as they would be for any other library. They are documented in the relevant sections of https://kotlinlang.org/docs/home.html

Also, not recommending using `kotlinx-datetime` from Native was not the point of that comment; there was a recommendation to use bridges to and from native entities to access our logic, but the other approaches are not "not recommended", they are perfectly fine as well if one is aware of the tradeoffs.

> I believe for the such mixed/legacy project only JSR 310 is the reliable way to go.

The question feels fairly easy. If you like the API of Java Time, then use that. If you need to access the date-time functionality from multiplatform code or like the API of this library more, use it instead.

If by reliability you mean lack of breakages, then, once our library leaves the pre-release stage, we will maintain backward compatibility, so sudden breakages won't happen, including the cases when the library is accessed from Java.
