### ISSUE TITLE
Release for Kotlin 1.6.0

### ISSUE THREAD

**Issue by akaraul** [Kotlin/kotlinx-datetime#162]
Please make new release for Kotlin 1.6.0 @ilya-g

**Comment by master-bytes-krafter** [comment]
Hello, any approximative ETA on this subject ? Thank you

**Comment by ilya-g** [comment]
Sorry for delay. We'll release a new version this week.

**Comment by ilya-g** [comment]
Done: https://github.com/Kotlin/kotlinx-datetime/releases/tag/v0.3.2
