### ISSUE TITLE
InstantSerializer: Passing an invalid string does not yield a SerializationException

### ISSUE THREAD

**Issue by florianmutter** [Kotlin/kotlinx-datetime#169]
Passing a string that is not a date (e.g. "abc") does not yield a `SerializationException`. Instead it will yield this exception:

    kotlinx.datetime.DateTimeFormatException: java.time.format.DateTimeParseException: Text 'abc' could not be parsed at index 0
    
In my opinion this excpetion should be wrapped in a `SerializationException` to be able to have generic error handling if deserialization fails.

**Comment by dkhalanskyjb** [comment]
When implementing the serializers, I relied on https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers for stylistic guidance. It doesn't mention `SerializationException` at all, I believe. We want to adhere to the expectations placed on the custom serializers.

cc @qwwdfsad

**Comment by qwwdfsad** [comment]
Thanks for pointing it out! 

Indeed the documentation has to be improved on `kotlin-serialization` side: https://github.com/Kotlin/kotlinx.serialization/issues/1875

**Comment by dkhalanskyjb** [comment]
According to the issue, us throwing `DateTimeFormatException: IllegalArgumentException` is stylistically correct, right?

**Comment by qwwdfsad** [comment]
Right, nothing wrong with it. If you throw it from within your serializer, it may be better to  throw `SE`, but it's the matter of style
