### ISSUE TITLE
Invalid .js export when using kotlinx.datetime: Module not found: Error: Can't resolve '@js-joda/core' 

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [Kotlin/kotlinx-datetime#183]
Version: 0.3.2 

In our KMM project, we use a simple export to javascript that only exposes 1 function:  `LibraryJs.test()`
```
@JsExport
@ExperimentalJsExport
class LibraryJs{    
   fun test(): String {
        val internalLib = InternalLib() 
        val result = internalLib.calculate()
        return result.text
    }
}
```

This works without the `kotlinx.datetime` library, it can be exported to js, imported & used in an angular project.

When adding `kotlinx.datetime`, as soon as InternalLib.calculate() includes a step where js-joda is used, e.g.  `val currentMoment = Clock.System.now()`, the JS library throws an error (on use, not on generation).

It can be successfully exported with: gradlew compileProductionExecutableKotlinJs

But when using this in an angular project, starting it with ng serve leads to following error:
`Module not found: Error: Can't resolve '@js-joda/core' in 'C:\GIT\kmm-project\shared\build\dist'`
(this folder includes the .js export file).

Including '@js-joda/core' in jsMain with `implementation(npm("@js-joda/core", "3.2.0"))`  or in the angular package.json does not help.

Is there anything additional that needs to be configured to use it in javascript?

**Comment by dkhalanskyjb** [comment]
Configuration-wise, this should be it, but https://discuss.kotlinlang.org/t/kotlin-js-1-4-how-to-output-a-npm-package/19128/4 seems to imply that the output of `compileProductionExecutableKotlinJs` is not sufficient on its own.

**Comment by KevinBassaDevelopment** [comment]
Solved, the issue was the path it searched for the js-joda module. By placing the export within the angular project it finds the module correctly (it searches only next & up to its  lib module location)
