### ISSUE TITLE
kotlinx.coroutines.test compatibility

### ISSUE THREAD

**Issue by sergeych** [Kotlin/kotlinx-datetime#185]
New kotlinx.coroutines.test provides smart and convenient`runTest {}` implementation, that provides sort of vurtual time, "eating" `delay()` calls and advancing "system" time accordingly, also providing `advanceTimeBy(duration)` convenienct method.

`Clock.System.Now()` as for now is not compatible with it so testing anything that uses kotlinx.datetime provides severe and hard to understand test-time bugs.

**Comment by dkhalanskyjb** [comment]
There's already a PR that would solve this that we're not sure about: https://github.com/Kotlin/kotlinx-datetime/pull/164

Do you maybe have some use cases not listed in https://github.com/Kotlin/kotlinx-datetime/pull/164#issuecomment-997801241?

**Comment by sergeych** [comment]
I'll try it, thank you.
