### ISSUE TITLE
API reference in Dokka or other tool

### ISSUE THREAD

**Issue by aftabahmadTW** [Kotlin/kotlinx-datetime#192]
Hi! Just wondering if there were plans to add support for the API reference in Dokka or another tool. This was done for the https://github.com/Kotlin/kotlinx.serialization with the docs available [here](https://kotlin.github.io/kotlinx.serialization/).

Are there plans to do the same with this library?

**Comment by Paxa** [comment]
Me too looking for some API documentation (So I don't have to see code all the time)
