### ISSUE TITLE
Could not find org.nodejs:node:14.17.0 for arm64

### ISSUE THREAD

**Issue by serbelga** [Kotlin/kotlinx-datetime#193]
**Steps to reproduce it**

Build project:

```
Could not determine the dependencies of task ':kotlinNodeJsSetup'.
> Could not resolve all files for configuration ':detachedConfiguration2'.
   > Could not find org.nodejs:node:14.17.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/nodejs/node/14.17.0/node-14.17.0.pom
       - https://nodejs.org/dist/v14.17.0/node-v14.17.0-darwin-arm64.tar.gz
```

**Device**

MacBook Pro 2021 - Apple M1 Pro

**Possible solution**

Updating Kotlin to 1.6.20 downloads nodejs 16.13.0 which is available for arm64.

**See**
https://youtrack.jetbrains.com/issue/KT-49109

**Comment by dkhalanskyjb** [comment]
Ok, but how is this related to our library?

**Comment by serbelga** [comment]
Currently, you are using Kotlin version 1.6.0. This issue seems to be resolved if you update to 1.6.20.

**Comment by dkhalanskyjb** [comment]
Ah, sorry, missed the first sencence of the issue. Thanks for the heads-up!

**Comment by serbelga** [comment]
I opened https://github.com/Kotlin/kotlinx-datetime/pull/194
