### ISSUE TITLE
DateTimeParseException issue persists

### ISSUE THREAD

**Issue by Somnium99** [Kotlin/kotlinx-datetime#195]
I'm trying to parse String datetime and suddenly getting this exception :

java.time.format.DateTimeParseException: Text '2022-04-03T09:17:08.256399+03:00' could not be parsed, unparsed text found at index 26

This might related to this issue :
https://github.com/Kotlin/kotlinx-datetime/issues/56
and:
https://github.com/Kotlin/kotlinx-datetime/issues/41

**Comment by dkhalanskyjb** [comment]
What type of object exactly are you trying to parse? `LocalDateTime.parse` won't work, because this string does not denote a `LocalDateTime`. Try `Instant.parse`.
