### ISSUE TITLE
java.lang.ClassNotFoundException: j$.time.ZoneOffset

### ISSUE THREAD

**Issue by sebleclerc** [Kotlin/kotlinx-datetime#197]
Hi! I am having this weird error when I try to instantiate a new TimeZone object:
```
val tz = TimeZone.of("America/Toronto")
```
and then use it here:
```
val now: LocalDate = Clock.System.todayAt(tz)
```

The error is reported from a user that has a Galaxy S20 Ultra 5G device with Android 12 (API level 31). I did some testing on my side with my Nexus 5 on Android 6.0.1 (API level 23) and it's working fine!

This core module is part of a Multiplatform module using Kotlin 1.6.20-M1 version and kotlinx date time version 0.3.1. Everything is working fine also on my emulator.

This is the latest part of the stacktrace:
```
kotlinx.datetime.UtcOffset.<clinit> UtcOffsetJvm.kt:23
kotlinx.datetime.TimeZone.<clinit> TimeZoneJvm.kt:35
core.models.Day$Companion.today Day.kt:15
```

**Comment by ilya-g** [comment]
The class name `j$.time.ZoneOffset` indicates that the java.time classes were desuraged. What I know about this process is that it links the desuraged API classes in a separate .dex. Maybe if you could check whether this .dex is present in the resulting apk and/or in the problematic device, it would give some further leads.

**Comment by dkhalanskyjb** [comment]
@sebleclerc, do you still have this issue?

**Comment by sebleclerc** [comment]
@dkhalanskyjb Thanks for the followup! 

I did update my code a bit since and I'm using:
```
val now = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())
```

And I just tried on 2 devices and don't have the crash. I've updated to kotlinx-datetime to 0.4.0 since.

What / if something was fixed but I don't have that crash anymore. I'll close for now and reopen if needed.
