### ISSUE TITLE
Cannot access class 'kotlinx.datetime.Instant'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by dusiema** [Kotlin/kotlinx-datetime#198]
I updated a bunch of dependencies in my multiplatform App project (Kotlin to 1.6.20, KotlinxSerialization to 1.3.2, ...) and after it the Android app started to have the problem: 
`Cannot access class 'kotlinx.datetime.Instant'. Check your module classpath for missing or conflicting dependencies`
This error message is from Android Studio - I also updated Android Studio.

Strange enough it does compile ok for the iOS App with `gradle createXCFramework`. But my test `scheme` in xCode also doesn't find the `Instant` Kotlin class anymore. 

I wonder if this is only me or if anyone else has experienced this?

**Comment by dusiema** [comment]
Thank you for your comment.
My minSDK is 21 (and this has not been changed). And I only updated a fairly new project (e.g. Kotlin from 1.6.0 to 1.6.20). So I'm not 100% sure but it seems that it has not to do with desugaring 1.8 Java language features? (I tried it anyways but it did not make a difference).

I also followed the "Using in your projects" guide and set `java.mainToolchainVersion` to `8`. But also without any luck.

**Comment by dkhalanskyjb** [comment]
It doesn't look like an Android issue, since it's the `kotlinx.datetime.Instant` class that can't be found, not `java.time.Instant`. Maybe there's just no runtime dependency on `kotlinx-datetime` now and there was one (transitively) before? Did you try explicitly adding
```kotlin
                 implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.3.2")
```
to your dependencies and resyncing the Gradle project?

**Comment by dusiema** [comment]
Unfortunately the dependency has already been explicitly specified like that.
Imho, it seems to be an Android Studio / Intellij issue and having to do with the Java Module Path (opposed to classpath).
So I guess it might not be directly related to kotlinx-datetime. 

I was just wondering if anybody else experienced this. 
Looking for a `module-info.java` I found this PR https://github.com/Kotlin/kotlinx-datetime/pull/135 which adds a `module-info.java` to `kotlinx-datetime`. But I don't know if and how it is related. Or if the issue is just on the Android Studio/Intellij side.

**Comment by dusiema** [comment]
I ran the build again but on command line with `./gradlew installDebug` and it had the same problem. 
Reading some about gradle build and classpath I learned that `api` and `implementation` affect the classpath. So I just gave

    api("org.jetbrains.kotlinx:kotlinx-datetime:0.3.2")
    
a try and then it compiled. I certainly do not fully oversee all  implications that `api` has over `implementation`. 
And the documentation on kotlinx-datetime says to use `implementation`. But I guess I stick with `api` for now. 

(Sorry for kind of miss-using a bug ticket for this. Feel free to close this ticket anytime. I might sooner or later close this ticket myself  if there are no other problems/ideas/comments.)

**Comment by dusiema** [comment]
Thanks for the explanation. I'm not writing a library and I'm not exposing anything from kotlinx-datetime. I'm actually just using `Instant`. After changing it to `api` I can change it back to `implementation` and it still works. 
There must be some kind of dependency resolution / classpath problem elsewhere. Anyways.
