### ISSUE TITLE
Mention LocalTime as part of 0.3.3 release

### ISSUE THREAD

**Issue by vanniktech** [Kotlin/kotlinx-datetime#199]
Or wasn't it released?

**Comment by joreilly** [comment]
I'm not seeing, using 0.3.3, `LocalTime` being available in for example common code of Kotlin Multiplatform project.

**Comment by vanniktech** [comment]
It was definitely merged: https://github.com/Kotlin/kotlinx-datetime/pull/187

**Comment by ilya-g** [comment]
The version [0.3.3](https://github.com/Kotlin/kotlinx-datetime/releases/tag/v0.3.3) doesn't include any features, it merely bumps dependency versions.
New features will be released in the version 0.4.0.

**Comment by joreilly** [comment]
Might be worth noting something in `README`...right now it shows this as being available.

**Comment by ilya-g** [comment]
@joreilly You mean that Maven Central badge showing 0.3.3 available and that it doesn't contain all the features described in the readme?
I believe this situation is inevitable when there are not yet released features in master, and we hardly can do anything about it beside bringing the development to a non-default branch, which we wouldn't want to at this point.

**Comment by joreilly** [comment]
Understood, just found it confusing when I started using library and tried to use code in `README`

**Comment by joreilly** [comment]
Might be worth noting something in README... right now it shows this as
being available.
