### ISSUE TITLE
Way for format a time currently?

### ISSUE THREAD

**Issue by joreilly** [Kotlin/kotlinx-datetime#200]
Given code like following (used in Android), is there way right now to do something equivalent in shared Kotlin Multiplatform code using Kotlinx Datetime (given a `LocalDateTime`)

```
        val date = df.parse(startDate)

        val timeFormatter = SimpleDateFormat("HH:mm")
        return timeFormatter.format(date)
```

**Comment by ilya-g** [comment]
No, there's no multiplatform way to format date and time with custom formats, only ISO-8601 is supported out of the box. 
The current workaround is to declare expect formatting functions and implement them with those actual formatting API available in the target platforms.
You can follow issues labelled with the https://github.com/Kotlin/kotlinx-datetime/labels/formatters label to track the state of formatting support in this library.
