### ISSUE TITLE
0.4.0 release date?

### ISSUE THREAD

**Issue by mikeholler** [Kotlin/kotlinx-datetime#203]
I see that #57 has been completed, and it is the only ticket in the 0.4.0 milestone. I would love to use this functionality in my project, but I would prefer not to use a master build. Any idea on timeline for a release?

**Comment by ilya-g** [comment]
We are going to release this version shortly after Kotlin 1.7.0.

**Comment by essarn** [comment]
Hi @ilya-g, so this will not be released for several months? (According to https://is.kotlin.released.info/)

**Comment by dkhalanskyjb** [comment]
1.7 is supposed to release much earlier: even the 1.7.0-beta version is already published. I wonder what this site bases its estimate on.

**Comment by essarn** [comment]
Is there any way to use a snapshot version in the meantime? Tried with jitpack but it could't build the project.

**Comment by wakaztahir** [comment]
Kotlin 1.7 is too far away , I think a beta version should be released which contains LocalTime, This is important because it contains LocalTime and I can finally say goodbye to many own platform dependent Time classes !

Please make it happen !

**Comment by JakeWharton** [comment]
1.7 just had an RC2. That website is not only unofficial, it's plain wrong. Don't use it.

**Comment by essarn** [comment]
Kotlin 1.7 is now released 🚀

**Comment by essarn** [comment]
@JakeWharton Hi again, is the release near in time now that Kotlin 1.7 has been released?

**Comment by JakeWharton** [comment]
No idea. I don't work on the team that maintains this project.

**Comment by essarn** [comment]
Really need this feature, is there something were waiting for? Thanks in advance!

**Comment by JakeWharton** [comment]
Consider depending on a snapshot or building the library yourself in the mean time.

https://www.zacsweers.dev/you-are-not-blocked/

**Comment by dkhalanskyjb** [comment]
Release 0.4.0 is out!
