### ISSUE TITLE
Type for Instant in time zone

### ISSUE THREAD

**Issue by Paxa** [Kotlin/kotlinx-datetime#217]
Would be nice to have type that keep exact point in time and timezone that we use for formatting it, will be helpful to calculate date in readable way

something like:

```kotlin
val tz = TimeZone.of("Asia/Jakarta")
val today = Clock.System.todayAt(tz).toZonedDateTime(tz) // beginning of today in my time zone

today.toString()                       // => 2022-06-21T00:00:00+07:00 - (ISO 8601 formatted)

val meetTime = today + 12.hours        // => 2022-06-21T10:00:00+07:00

// other user may have different time zone settings
meetTime.toString(TimeZone.of("Europe/Moscow")) // => 2022-06-21T08:00:00+03:00

db.saveTime(meetTime.toSqlTimestamp()) // => 2022-06-21T05:00:00Z
```

May be there is already something like that, which I missed?

**Comment by dkhalanskyjb** [comment]
There's no such functionality built in at the moment, but for formatting an `Instant` with a chosen offset, you can do something like this:
```kotlin
fun Instant.toString(timeZone: TimeZone) =
    "${toLocalDateTime(timeZone)}${offsetIn(timeZone)}"
```
If you need the type for something other than formatting, please share it here: https://github.com/Kotlin/kotlinx-datetime/issues/163
