### ISSUE TITLE
how to get current local epoch time 

### ISSUE THREAD

**Issue by periva101** [Kotlin/kotlinx-datetime#219]
Clock.System.now() //utc time stamp
 .toLocalDateTime(TimeZone.currentSystemDefault()) localdate
.toInstant() //utc again 

I want to pass the current timestamp to the server in localtime
something like System.currentTimeMillis()

**Comment by dkhalanskyjb** [comment]
Please use the Kotlin Slack for general questions.

I don't understand the question, but if you want the equivalent of `System.currentTimeMillis()`, you can do `Clock.System.now().toEpochMilliseconds()`.
