### ISSUE TITLE
Expose Instant.MIN & Instant.MAX

### ISSUE THREAD

**Issue by vanniktech** [Kotlin/kotlinx-datetime#227]
Would it be possible to expose `Instant.MIN` & `Instant.MAX`. 

My use is for filtering. For instance you can get all events, or only within a certain range (6 hours ago, 24 hours ago, etc.) If I have a time range, I can use that and otherwise I'd like to use `Instant.MIN` & `Instant.MAX`.

So essentially, `range?.from ?: Instant.MIN` & `range?.to ?: Instant.MAX`.

**Comment by dkhalanskyjb** [comment]
```kotlin
filter { instant -> (from == null || from <= instant) && (to == null || to >= instant) }
filter { instant -> (from ?: Instant.MIN) <= instant && (to ?: Instant.MAX) >= instant }
```
I don't see what you're going to win from this. Character-count-wise, these are completely identical, and I don't think the first one is less clear.

**Comment by vanniktech** [comment]
Maybe I should have been more clear but querying happens on database layer (using sqldelight) and there I can only pass `Instant`. So I can't null check, instead I need to create an Instant.

```kotlin
    return queryWrapper.itemQueries.favoriteCount(
      channelIds = filter.channels.orEmpty(),
      channelIdsEmpty = filter.channels.isNullOrEmpty(),
      betweenLow = range?.from ?: Instant.fromEpochMilliseconds(0),
      betweenHigh = range?.to ?: Instant.fromEpochMilliseconds(Long.MAX_VALUE),
    ).observeSingle(callback)
```

**Comment by vanniktech** [comment]
Alright, that seems good!

**Comment by ilya-g** [comment]
Please also note that different databases may have different acceptable ranges of their date/time types, so even `DISTANT_PAST` and `DISTANT_FUTURE` constants may be out of that range. I believe it makes sense to define your own constants for these bounds taking into account the limits imposed by the database.
