### ISSUE TITLE
Instant.EPOCH

### ISSUE THREAD

**Issue by Nek-12** [Kotlin/kotlinx-datetime#236]
This is simple: could we add an equivalent of java.time.Instant.EPOCH? 
This would be a static equivalent of  

```
val Instant.Companion.EPOCH: Instant
    get() = fromEpochMilliseconds(0)
```

**Comment by elizarov** [comment]
What kind of usage do you have in mind for it?

**Comment by Nek-12** [comment]
I'm sometimes modeling last updated property of an object as EPOCH by default because I don't want to make the field nullable. EPOCH would represent a value that would make the model "old" immediately. Since databases or other libraries might not support the exact level of precision that Instant.MIN provides, it's safer to go with EPOCH.

**Comment by dkhalanskyjb** [comment]
See https://github.com/Kotlin/kotlinx-datetime/issues/227. The same discussion applies to your use case: `Instant.EPOCH` is not, logically, a minimum value. Using `Instant.EPOCH` for this would obscure the meaning of the code, leading to doubt about its correctness. "This value was last changed in 1970, that is, never" sounds absurd if you're out of context, even if the reader knows that `EPOCH` is the Unix epoch and not, say, the Apple reference date, which is in 2001, or something else entirely.

Why don't you want the field to be nullable? If there is actually no last-changed value present, then doing anything with it other than updating is likely a mistake. Making it nullable forces you to think about what would happen if you access it when there's nothing there. This would prevent embarrassing bugs like showing `1970-01-01` to your users.

In any case, what you want to write can be written in a more semantically clear fashion, for example, like this:
```kotlin
/**
 * We believe that no changes to models happen earlier than this instant.
 * So, this value is used as a placeholder for "there have never been any changes" in the model-was-last-changed fields.
 */
internal val Instant.Companion.BEFORE_ANY_CHANGES: Instant
    get() = fromEpochSeconds(0)
```

**Comment by Nek-12** [comment]
Okay, it wasn't pleasant to admit, but after some research I have come to the conclusion that I should indeed represent "unchanged yet" values as NULLs, so for my particular use-case, usage of EPOCH does not apply anymore. 

Other things to consider here is parity with the java.time library (which has an EPOCH constant) and other possible use-cases that weren't reported yet.

If there are no plans on implementing this, the issue may be closed
