### ISSUE TITLE
Parse ISO8601 date/times without punctuation

### ISSUE THREAD

**Issue by brianguertin** [Kotlin/kotlinx-datetime#240]
It looks like parsing only works if the string contains `-` and `:` characters, but these are actually optional in ISO8601.

For example, this local date/time should parse fine, but doesn't:
`LocalDateTime.parse("20221025T0600")`

**Comment by dkhalanskyjb** [comment]
Kind of. You can't say, for example, `2022-10-25T0600`. There are two separate kinds of ISO-8601 formats: the basic one (the one you're requesting) and the extended one (the one we support). You're right though that we should document in our `parse` functions that they only support the extended format.
