### ISSUE TITLE
Considering the possibility to represent `0` of some `DateTimeUnit`?

### ISSUE THREAD

**Issue by kevincianfarini** [Kotlin/kotlinx-datetime#246]
Right now all of the instances of `DateTimeUnit` guard against instantiating with zero of the underlying asset. For example: 

```kt
@Serializable(with = DayBasedDateTimeUnitSerializer::class)
public class DayBased(
    /**
     * The length of this unit in days.
     */
    public val days: Int
) : DateBased() {
    init {
        require(days > 0) { "Unit duration must be positive, but was $days days." }
    }
```

This feels really unintuitive. If someone is dynamically performing math operations of `Instant`, `LocalDate`, etc. it should be permissible to have an identity operation. Currently this requires null coalescing for identity-like operations. Eg: 

```kt
val dateTimeUnit: DateTimeUnit? = /* TODO */
val date = clock.now().toLocalDate(/* omitted */).let { date ->
  if (dateTimeUnit == null) date else date.minus(dateTimeUnit)
} 
```  

I'm hoping to understand the rationale for why zero of some `DateTimeUnit` is generally prohibited. Thank you!

**Comment by ilya-g** [comment]
`DateTimeUnit` is not an alternative for `Duration` or `DateTimePeriod`. If you want to add zero of some `DateTimeUnit`, use the overload that takes an integer and that `DateTimeUnit`.
We're considering deprecating the overloads of `plus` and `minus` with a single `DateTimeUnit` parameter to avoid this confusion, see https://github.com/Kotlin/kotlinx-datetime/issues/95#issuecomment-767375456

**Comment by kevincianfarini** [comment]
That makes more sense, thank you!
