### ISSUE TITLE
Publish API documentation

### ISSUE THREAD

**Issue by sdeleuze** [Kotlin/kotlinx-datetime#255]
As a follow-up of #192, could you please publish the API documentation generated  with Dokka somewhere, maybe on https://kotlinlang.org/api/ like [kotlinx.serialization](https://kotlinlang.org/api/kotlinx.serialization/)?

Would be nice to add a related badge or link in the README.

**Comment by dkhalanskyjb** [comment]
https://kotlinlang.org/api/kotlinx-datetime/

**Comment by sdeleuze** [comment]
Nice, any chance you could add a related badge in the README, like https://github.com/Kotlin/kotlinx.serialization does, to improve the discoverability of such documentation?
