### ISSUE TITLE
Instant.parse method bad examples

### ISSUE THREAD

**Issue by Catah97** [Kotlin/kotlinx-datetime#258]
Function `Instant.parse` in Instant.kt file has bad input examples.
https://github.com/Kotlin/kotlinx-datetime/blob/fea8ce80cf6e4d96b06aa1eb187c52e9966aac6c/core/common/src/Instant.kt

Current examples are:

Examples of instants in the ISO-8601 format:
- 2020-08-30T18:43:00Z
- 2020-08-30T18:43:00.500Z
- 2020-08-30T18:43:00.123456789Z
- 2020-08-30T18:40.00+03:00
- 2020-08-30T18:40.00+03:30:20

The last two examples are not correct and if you pass them to the function `IllegalArgumentException` is thrown.

Examples should be:
- 2020-08-30T18:40:00+03:00
- 2020-08-30T18:40:00+03:30:20

In both `.` was been replaced with `:` between minutes and seconds.

**Comment by dkhalanskyjb** [comment]
Thanks!
