### ISSUE TITLE
Bug in `Instant.plus(Duration)` on JS for large `Instant`s and small `Duration`s

### ISSUE THREAD

**Issue by Lukellmann** [Kotlin/kotlinx-datetime#263]
Running this code on JS produces an unexpected result
```kt
val instant = Instant.fromEpochMilliseconds(Long.MAX_VALUE) + 999_999.nanoseconds
println(instant) // expected some positive (clamped) value, got -1000000-01-01T00:00:00Z
```
The reason for this seems to be [this line of code](https://github.com/Kotlin/kotlinx-datetime/blob/cd6dcd1abb547bc90455471e644e1e8fe2a49e5c/core/js/src/Instant.kt#L38).
1) `Instant.fromEpochMilliseconds(Long.MAX_VALUE)` gives the max instant on JS (`+1000000-12-31T23:59:59.999999999Z`)
2) [`plusFix`](https://github.com/Kotlin/kotlinx-datetime/blob/cd6dcd1abb547bc90455471e644e1e8fe2a49e5c/core/js/src/Instant.kt#LL42C18-L42C25) overflows and throws a `DateTimeException`
3) [here](https://github.com/Kotlin/kotlinx-datetime/blob/cd6dcd1abb547bc90455471e644e1e8fe2a49e5c/core/js/src/Instant.kt#L38) is the actual bug: because the added amount is smaller than one second, `seconds` is `0`, resulting in `Instant.MIN` being returned

The line should probably be something like this instead:
```kt
if (duration.isPositive()) MAX else MIN
```

**Comment by Lukellmann** [comment]
This _might_ also apply to [native](https://github.com/Kotlin/kotlinx-datetime/blob/cd6dcd1abb547bc90455471e644e1e8fe2a49e5c/core/native/src/Instant.kt#L162) (haven't tested it though), [jvm](https://github.com/Kotlin/kotlinx-datetime/blob/cd6dcd1abb547bc90455471e644e1e8fe2a49e5c/core/jvm/src/Instant.kt#L42) seems fine.

**Comment by Lukellmann** [comment]
Can confirm that it also happens on native, will open a PR to fix this.

**Comment by 05nelsonm** [comment]
I *believe* my issue might be related to this issue, but wanted to check before opening a ticket.

The value was produced on `jvm`. Converting from a `String` back to an `Instant` works fine.

```kotlin
"+5881633-11-04T10:50:52.288260993Z".toInstant()
````

On native though converting that same `String` to an `Instant` throws a `DateTimeFormatException`.

**Comment by dkhalanskyjb** [comment]
@05nelsonm it's not related, Native and JS support a much smaller range of years than JVM, namely years `±1000000` at most, instead of `±1000000000` for the JVM. We didn't consider dates outside the smaller range to be useful in practice.

**Comment by 05nelsonm** [comment]
Thanks. Will open a separate ticket then.
