### ISSUE TITLE
Unable to parse ISO 8601 valid datetime if it ends with Z

### ISSUE THREAD

**Issue by H4kt** [Kotlin/kotlinx-datetime#265]
Stumbled upon this while receiving `2023-04-06T14:28:00.000Z` from a web front-end
As per ISO standard UTC date time should actually end with a dangling `Z` ([wiki](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)))

Here's a quick example:
```kotlin
fun main() {
    LocalDateTime.parse("2023-04-06T14:28:00.000Z")
}
```

Throws:
```
Exception in thread "main" kotlinx.datetime.DateTimeFormatException: java.time.format.DateTimeParseException: Text '2023-04-06T14:28:00.000Z' could not be parsed, unparsed text found at index 23
	at kotlinx.datetime.LocalDateTime$Companion.parse(LocalDateTime.kt:62)
```

**Comment by dkhalanskyjb** [comment]
Use `Instant.parse` instead.

**Comment by H4kt** [comment]
> Use `Instant.parse` instead.

That's not the solution.
Dates should follow the standard.

**Comment by dkhalanskyjb** [comment]
They do. `LocalDateTime` represents "calendar date and local time of day," whereas `Instant` represents "date and UTC of day," using the ISO-8601 terms.
