### ISSUE TITLE
Support Kotlin/Wasm target for JS environments (browser, nodejs)

### ISSUE THREAD

**Issue by bmalkow** [Kotlin/kotlinx-datetime#267]
Would you like to add `wasm` target to library, please?

**Comment by bashor** [comment]
Reopened since we may have different implementations for JS and WASI environments

**Comment by chris-hatton** [comment]
I found [this](https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/org/jetbrains/kotlinx/kotlinx-datetime/0.4.0-wasm1/), but cannot get it to work.  When used with Kotlin `1.9.0` at least, there's an issue resolving **jodatime** dependency at runtime.  See this [Slack thread](https://kotlinlang.slack.com/archives/CDFP59223/p1688638360198979).

**Comment by bashor** [comment]
PR #315

**Comment by dkhalanskyjb** [comment]
Closed in https://github.com/Kotlin/kotlinx-datetime/commit/841b0a895e8f8b23bdb0ba4f397273e71743e10f
