### ISSUE TITLE
Instant.fromEpochMilliseconds(origin.toEpochMilliseconds()) should be origin

### ISSUE THREAD

**Issue by olegivo** [Kotlin/kotlinx-datetime#270]
version: 0.4.0

```kotlin
        "fromEpochMilliseconds(origin.toEpochMilliseconds()) should be origin" {
            val origin: Instant = Clock.System.now()

            val encoded = origin.toEpochMilliseconds()
            val decoded = Instant.fromEpochMilliseconds(encoded)

            decoded shouldBe origin
        }

```

output:  
>expected:<2023-04-27T13:56:21.779783Z> but was:<2023-04-27T13:56:21.779Z>
Expected :2023-04-27T13:56:21.779783Z
Actual   :2023-04-27T13:56:21.779Z

**Comment by dkhalanskyjb** [comment]
By using "milliseconds" you're truncating the precision to milliseconds. If you want to preserve microseconds, use https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/-companion/from-epoch-seconds.html, it accepts nanoseconds as the second argument.

**Comment by dkhalanskyjb** [comment]
You should use https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/epoch-seconds.html and https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/nanoseconds-of-second.html.

**Comment by olegivo** [comment]
Thank you. Or if I don't need that accuracy, I can just round it  
`origin - origin.nanosecondsOfSecond.nanoseconds`  
and use to/from EpochMilliseconds
