### ISSUE TITLE
Instant.minus(other: Instant): Duration incorrect for time change 

### ISSUE THREAD

**Issue by Ronron1024** [Kotlin/kotlinx-datetime#272]
```kotlin
val i1: Instant = Instant.parse("2023-03-26T00:00:00+02:00")
val i2: Instant = Instant.parse("2023-03-27T00:00:00+02:00")

println(i1.periodUntil(i2, TimeZone.of("Europe/Paris")))
println((i2 - i1).inWholeHours)
```

Output of this code is inconsistent:

```
P1DT1H
24
```

According to [the doc](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/), **Duration**:

> Represents the amount of time one instant of time is away from another instant.

The amount of time between **2023-03-26T00:00:00+02:00** and **2023-03-27T00:00:00+02:00** is **25 hours**, due to _time change from winter time to summer time_.

What are you thoughts on this ?

**Comment by dkhalanskyjb** [comment]
The output is consistent: in Paris, the clocks would make a whole day's worth of advancement and also an hour to account for the DST change.

> The amount of time between 2023-03-26T00:00:00+02:00 and 2023-03-27T00:00:00+02:00 is 25 hours

It's not, it's 24 hours. `+02:00` is the same thing, 2 hours off the Greenwich time, regardless of which timezone you observe it from.

**Comment by Ronron1024** [comment]
My bad, I confused between GMT and UTC

**Comment by dkhalanskyjb** [comment]
You didn't, they are the same.

**Comment by Ronron1024** [comment]
Okay so now I am confused !

At the instant 2023-03-27T00:00:00+02:00, what will be the time indicated by the clocks in Paris ?

**Comment by dkhalanskyjb** [comment]
```kotlin
Instant.parse("2023-03-27T00:00:00+02:00").toLocalDateTime(TimeZone.of("Europe/Paris")) // 2023-03-27T00:00
```

**Comment by Ronron1024** [comment]
And:
```kotlin
Instant.parse("2023-03-26T00:00:00+02:00").toLocalDateTime(TimeZone.of("Europe/Paris")) // 2023-03-25T23:00
```
So it's all good !

Could you please provide a document/reference that explain clearly what are UTC, GMT, Time Zone ? It will help me and I hope others to consolidate the comprehension of this library.

**Comment by dkhalanskyjb** [comment]
Reading through the README here https://github.com/Kotlin/kotlinx-datetime is a good starting point, and the API reference should provide all the details: https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/ If something's missing, please open an issue, we do try to keep the documentation approachable.
