### ISSUE TITLE
How to format some types of date

### ISSUE THREAD

**Issue by Garf1eldGit** [Kotlin/kotlinx-datetime#276]
Here is example of strings, those i want to format into some type of date.

    "2020-02-04T09:07:13.851+0300"
    "17.01.2022"
    
With  ```Instant.parce("2020-02-04T09:07:13.851+0300") ```  throws exception     ```could not be parsed, unparsed text found at index 26```
And
```LocalDate.parse( "17.01.2022")```  throws ```Text '17.01.2022' could not be parsed at index 0```

How to do it nicely?

**Comment by Antimonit** [comment]
If I am not mistaken, this is not yet implemented.

From the readme:
> Currently, `Instant`, `LocalDateTime`, `LocalDate` and `LocalTime` only support ISO-8601 format.

Also from the readme:
> ## Known/open issues, work TBD
> [x] Some kind of Clock interface is needed as a pluggable replacement for Instant.now().
> [ ] Flexible locale-neutral parsing and formatting facilities are needed to support various date/time interchange formats that are used in practice (in particular, various RFCs).

Only ISO formats are now supported for now. In your case, it needs to be formatted as:

```kt
LocalDate.parse("2022-01-17")
Instant.parse("2020-02-04T09:07:13.851+03:00")
```
