### ISSUE TITLE
Building in terminal with "kotlinc test.kt -include-runtime -d test.jar -cp kotlinx-datetime-jvm-0.3.1.jar" produces "java.lang.ClassNotFoundException"

### ISSUE THREAD

**Issue by g3th** [Kotlin/kotlinx-datetime#280]
When building in linux terminal only (Kali Linux/Debian), using kotlin compiler, the datetime library does not function as intended.

Most methods (i.e. Clock) return a class not found exception. Including other libraries, like gradle does, in classpath (i.e. trove4j-1.0.20200330.jar:kotlin-tooling-metadata-1.6.21.jar) will not work, and produce the same error.

For instance, this:

val currentTime = Clock.System.now().toLocalDateTime(TimeZone.of("UTC+1")).date

produces this stacktrace:

Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/datetime/Clock$System
	at TestKt.main(test.kt:4)
	at TestKt.main(test.kt)
Caused by: java.lang.ClassNotFoundException: kotlinx.datetime.Clock$System
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by dkhalanskyjb** [comment]
Please use StackOverflow or Kotlin Slack for general usage questions. This issue tracker is for tracking issues with the library. The datetime library doesn't do any special trickery that could cause this, and it works in most scenarios, so it's most likely just a misconfiguration on your part.

One guess would be that you are only passing the classpath to the compiler (as shown in the CLI invocation in the issue's title) but not in runtime. The runtime classpath and the compile-time classpath are different things; for JVM, the compilation does not statically link the libraries.

**Comment by g3th** [comment]
Sorry about that. Adding classpath at runtime fixed it, sorry for wasting your time:

java -classpath test.jar:kotlinx-datetime-jvm-0.3.1.jar:kotlinx-datetime-jvm-0.3.1.jar, TestKt

I initially posted this because someone mentioned it would be similar to the desugaring issue encountered in Android, but mine was user-error and that was not the case.
