### ISSUE TITLE
Day of week in narrow format should be X for Spanish

### ISSUE THREAD

**Issue by barry-irvine** [Kotlin/kotlinx-datetime#294]
When showing dates in short format, Spanish calendars should show X for Wednesday instead of M for Miercoles to distinguish it from M for Martes (Tuesday). Using TextStyle.NARROW_STANDALONE gives a numeric value so I assume that TextStyle.NARROW is correct.

E.g `localDateTime.dayOfWeek.getDisplayName(TextStyle.NARROW, Locale.forLanguageTag("es-ES"))` should give X for Wednesday not M.

I've had to resort to using Android's DateFormatSymbols instead:

    val daysOfWeek = DateFormatSymbols.getInstance(Locale.getDefault())
        .getWeekdays(DateFormatSymbols.STANDALONE, DateFormatSymbols.NARROW)
    daysOfWeek[localDateTime.dayOfWeek.isoDayNumber]

**Comment by dkhalanskyjb** [comment]
`getDisplayName` is not a part of this library.
