### ISSUE TITLE
Missing classes detected while running R8 / Proguard

### ISSUE THREAD

**Issue by MarcelReiter** [Kotlin/kotlinx-datetime#297]
Attempting to obfuscate and shrink any android app that uses `Instant` results in the following errors

```
Missing classes detected while running R8. 
Please add the missing classes or apply additional keep rules that are generated in
.../app/build/outputs/mapping/release/missing_rules.txt.
```

The file mentioned contains:
```
-dontwarn kotlinx.serialization.KSerializer
-dontwarn kotlinx.serialization.Serializable
```

**To Reproduce**

1. Create a new Android app.
2. Add the following dependency: implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.4.0").
3. Create a new class which includes a field that is of type "Instant" and use it somewhere.
4. Attempt to obfuscate and shrink the app in release.

**Minimal sample**
See this github project: https://github.com/MarcelReiter/dateTimeTest
You NEED to build it in release mode.
Also i made nice small commits so it's understandable what i'm doing

**Environment**
- Kotlin version: 1.8.10
- Library version: 0.4.0
- Kotlin platforms: Android JVM

A nearly identical issue has been created by someone else in the `kotlinx.serialization` github:
https://github.com/Kotlin/kotlinx.serialization/issues/2392 - but it seems like it is `kotlinx.datetime` related

**Comment by matejbart** [comment]
The current `kotlinx.datetime` version `0.4.0` is based on `kotlinx.serialization` version `1.3.2`, so one option is to explicitly bump the `kotlinx.serialization` version to the latest stable version `1.5.1` that already contains the proguard rules (see [release notes v1.5.0-RC](https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.5.0-RC)) to fix these issues.

**Comment by ilya-g** [comment]
@matejbart Not sure it would help. `kotlinx-serialization` is used as a compile time dependency in JVM variant of `kotlinx-datetime` and therefore is not propagated transitively to dependees, so it's irrelevant which rules it contains.

**Comment by MarcelReiter** [comment]
I have updated to `kotlinx.datetime` 0.4.1 which includes an update of `kotlinx.serialization` to 1.5.1.
However, the issue still exists. Can someone confirm?

**Comment by VitaliyBelyaev** [comment]
I have updated to `kotlinx.datetime` to 0.5.0 which uses `kotlinx.serialization` 1.6.2 as I see in External libraries section in Android Studio, but issue with R8 still exists.

**Comment by VitaliyBelyaev** [comment]
As workaround, I've added `kotlinx.serialization` explicitly to the project: plugin and dependency version 1.6.2 to the android app and issue with R8 gone.

I think that proguard rules from `kotlinx.serialization` were applied and that fixed issue.

Maybe some or all rules from `kotlinx.serialization` should be added to `kotlinx.datetime` library for those who needs `kotlinx.datetime` but don't uses `kotlinx.serialization`.

**Comment by ilya-g** [comment]
>  I've added `kotlinx.serialization` explicitly to the project: plugin and dependency version 1.6.2 to the android app and issue with R8 gone.
> I think that proguard rules from kotlinx.serialization were applied and that fixed issue.

The workaround helped because the classes that R8 reported as missing are now found in the `kotlinx.serialization` dependency you've added.

**Comment by bdelville** [comment]
The same error occurred for my case when referencing a AAR built from a KMM library that uses datetime.
To fix it, simply add the implementation into the Android project:

`implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.5.0")`

**Comment by dkhalanskyjb** [comment]
@abbasnaqdi , please show us the specific error (which classes are missing). Also, does your project still work, despite the missing classes? If you send us a project where the issue reproduces, we will look into this.
