### ISSUE TITLE
I can't get the offset between my and given timezone.

### ISSUE THREAD

**Issue by pavlo-kravchenko** [Kotlin/kotlinx-datetime#301]
```
TimeZone.currentSystemDefault()                                 // Europe/Ukraine it is UTC +3 now
currentMoment.offsetIn(TimeZone.of("UTC+0")).totalSeconds       // 0 but I wait 3 * 60 * 60 * 1000
```

Am I missing something or is the code not working as expected?
How can I get the difference between my timezone and the given one?

**Comment by ilya-g** [comment]
> Am I missing something or is the code not working as expected?

The code works as expected. `currentMoment` is an instant and has no information in which time zone it was obtained. Calling `.offsetIn(TimeZone.of("UTC+0"))` will always return `UtcOffset(hours = 0)`.

> How can I get the difference between my timezone and the given one?

Something like:
```
currentMoment.offsetIn(TimeZone.currentSystemDefault()).totalSeconds - currentMoment.offsetIn(otherTimeZone).totalSeconds
```

**Comment by pavlo-kravchenko** [comment]
That's exactly what I did. But it looks weird.
