### ISSUE TITLE
Can't install 0.4.1

### ISSUE THREAD

**Issue by Hum4n01d** [Kotlin/kotlinx-datetime#303]
Version not found on Maven

**Comment by ilya-g** [comment]
Please be patient, it's not released yet. You'll see it in https://github.com/Kotlin/kotlinx-datetime/releases page when it is ready.

**Comment by Hum4n01d** [comment]
I recommend waiting to update the README until the package is published then, I spent a while trying to figure out why I couldn't install according to the instructions

**Comment by ilya-g** [comment]
The version 0.4.1 is released, you can use it now.

**Comment by Hum4n01d** [comment]
Thank you!
