### ISSUE TITLE
kotlinx.datetime.DateTimeFormatException

### ISSUE THREAD

**Issue by savan-ixfi** [Kotlin/kotlinx-datetime#306]
<img width="1245" alt="image" src="https://github.com/Kotlin/kotlinx-datetime/assets/131661149/3f3673b0-ca1f-48c5-ab7c-afc13b7235ae">

**Comment by ilya-g** [comment]
The string `2023-09-25` doesn't represent an `Instant`, but it can be parsed to a `LocalDate`. 
See the examples of parseable strings in the readme: https://github.com/Kotlin/kotlinx-datetime#converting-instant-and-local-datetime-to-and-from-string

**Comment by savan-ixfi** [comment]
> The string `2023-09-25` doesn't represent an `Instant`, but it can be parsed to a `LocalDate`. See the examples of parseable strings in the readme: https://github.com/Kotlin/kotlinx-datetime#converting-instant-and-local-datetime-to-and-from-string

Any example to parse date to given format and from this format to date?

**Comment by ilya-g** [comment]
Please take a look at the readme section link I posted, it contains an example how to parse exactly that format to `LocalDate`. And regarding formatting, you can use `.toString()` function to turn a `LocalDate` to a string in that format.
