### ISSUE TITLE
Add comparison operators for Instants/LocalDateTime

### ISSUE THREAD

**Issue by twatzl** [Kotlin/kotlinx-datetime#312]
A very common use case is to compare two instants if A is before B or A is after B and so on.

As far as I could see this is neither implemented nor has an issue be opened for this so far.

The idea would be to extend the library to allow to do something like this

```
val a: Instant = ...
val b: Instant = ...

if (a.isBefore(b)) {
    // do something
}

if (a.isAfter(b)) {
     // do something else
}
```

**Comment by twatzl** [comment]
Hmm. Ok it. It seems to be working with < and >, but I could not find any mention of this in the readme.md file.

Maybe it's just a documentation issue.

![image](https://github.com/Kotlin/kotlinx-datetime/assets/18753370/0360dd6d-273b-42d5-8d57-9c42160ce7f2)

**Comment by dkhalanskyjb** [comment]
Yeah, README.md doesn't list all available APIs; it only lists enough examples to form a conceptual model around the entities. The API reference is available at https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/
