### ISSUE TITLE
Could these extensions be added ?

### ISSUE THREAD

**Issue by wakaztahir** [Kotlin/kotlinx-datetime#329]
```kotlin
fun LocalDateTime.copy(
    year: Int = this.year,
    monthNumber: Int = this.monthNumber,
    dayOfMonth: Int = this.dayOfMonth,
    hour: Int = this.hour,
    minute: Int = this.minute,
    second: Int = this.second,
    nanosecond: Int = this.nanosecond
) = LocalDateTime(
    year = year,
    monthNumber = monthNumber,
    dayOfMonth = dayOfMonth,
    hour = hour,
    minute = minute,
    second = second,
    nanosecond = nanosecond
)

fun Instant.atTime(
    hour: Int,
    minute: Int,
    second: Int,
    nanosecond: Int,
    zone: TimeZone = TimeZone.currentSystemDefault()
) = toLocalDateTime(zone).copy(
    hour = hour,
    minute = minute,
    second = second,
    nanosecond = nanosecond
).toInstant(zone)
```

**Comment by wakaztahir** [comment]
`Instant.atDate` would also be good

**Comment by dkhalanskyjb** [comment]
Not in this form, but if you explain your use case, we could potentially add something other than this to help you.

**Comment by wakaztahir** [comment]
I use the copy extension multiple times, I just thought it would be good to have it

Also `atTime` and `atDate` are helpful if you are looking for a quick way to modify Instant with date and time

I just think they'd be helpful

**Comment by dkhalanskyjb** [comment]
Examples of use cases:
* Finding the last time it was Monday to understand if two days are on the same week,
* Setting the seconds and nanoseconds to zero for printing,
* Finding the same date/time in a different year.

Essentially, the question is, why do you think they'd be helpful?

**Comment by wakaztahir** [comment]
for modification of date ofcourse (for easy way of doing it) that's why its helpful (I think), HOW ?

everytime I need to only change the `day` in a `LocalDateTime` object I must create it completely, meaning I will call the constructor with all parameters specified, This is a lot verbose, just for changing the day

```kotlin
val time : LocalDateTime = ~
val newTime = time.copy(dayOfMonth = 8)
```

```kotlin
val time : LocalDateTime = ~
val newTime = LocalDateTime(
    year = year,
    monthNumber = monthNumber,
    dayOfMonth = 8,
    hour = hour,
    minute = minute,
    second = second,
    nanosecond = nanosecond
)
```

**Comment by dkhalanskyjb** [comment]
Why do you need to change the day?

**Comment by wakaztahir** [comment]
because user said he wants, but the question is why does he want to do it ? 😂

**Comment by dkhalanskyjb** [comment]
So, your user asked you: "I like everything, but please, replace these dates with those where the day of the month is 8, 16, and 23 because I simply like these numbers. You don't need to know anything else." Is this what happened?

**Comment by wakaztahir** [comment]
Okay, I was being sarcastic, User asked me to add a reminder, After two days, I added two days to my date time, User can also select weeks, months, having these extensions made it easier, thought I'd just post it here

**Comment by dkhalanskyjb** [comment]
To add two days, you can do `date.plus(2, DateTimeUnit.DAY)`, there's no need to implement addition manually.

As for "selecting weeks," I still don't understand what you mean.

**Comment by wakaztahir** [comment]
Do you think I could replace this code with something from the library

```
val tomorrowStart = currentInstant.atTime(23, 59, 59, 0)
val tomorrowEnd = currentInstant.plus(1.days).atTime(23, 59, 0, 0)
```

**Comment by dkhalanskyjb** [comment]
`plus(1.days)` is incorrect, it ignores DST transitions. Please use `plus(1, DateTimeUnit.DAY, zone)` instead.

I'd implement it somehow like this, probably:
```kotlin
val tomorrowStart = currentInstant.plus(1, DateTimeUnit.DAY, zone) - 1.seconds
val tomorrowEnd = currentInstant.plus(2, DateTimeUnit.DAY, zone) - 1.minutes
```

A more robust approach that takes DST transitions near midnight into account:
```kotlin
val tomorrowStart = currentInstant.toLocalDate(zone).date.plus(1, DateTimeUnit.DAY).atStartOfDay(zone) - 1.seconds
val tomorrowEnd = currentInstant.toLocalDate(zone).date.plus(2, DateTimeUnit.DAY).atStartOfDay(zone) - 1.minutes
```
