### ISSUE TITLE
Not compliant with ISO-8601

### ISSUE THREAD

**Issue by ShmuelCammebys** [Kotlin/kotlinx-datetime#341]
I am interfacing with an API written using the C# date/time stdlibs, and times are occasionally returned as the string "0001-01-01T00:00:00" (`System.DateTime.MinValue.ToString("o")`). This is officially ISO-8601 compliant, but I get this error because there is no time zone information:
```log
kotlinx.datetime.DateTimeFormatException: java.time.format.DateTimeParseException: Text '0001-01-01T00:00:00' could not be parsed at index 19
	at kotlinx.datetime.Instant$Companion.parse(Instant.kt:72)
```
Can't Instant assume it is UTC if no timezone is specified?

Here is the documentation on the "o" format:
![image](https://github.com/Kotlin/kotlinx-datetime/assets/144174211/7f0d2b85-d7f1-4fdf-ba33-f024f4d248eb)

**Comment by dkhalanskyjb** [comment]
> This is officially ISO-8601 compliant

It's an ISO-8601 compliant date + time, not instant.

> Can't Instant assume it is UTC if no timezone is specified?

It can't. Please specify it yourself if you want to.

```kotlin
LocalDateTime.parse(yourText).toInstant(TimeZone.UTC)
```
