### ISSUE TITLE
Issue including the library in kotlinjs project using gradle

### ISSUE THREAD

**Issue by 3bdoelnaggar** [Kotlin/kotlinx-datetime#35]
I get this error in build 
Could not determine the dependencies of task ':packageJson'.
> Could not resolve all dependencies for configuration ':npm'.
   > Could not resolve org.jetbrains.kotlinx:kotlinx-datetime:0.1.0.
     Required by:
         project :
      > Cannot choose between the following variants of org.jetbrains.kotlinx:kotlinx-datetime:0.1.0:
          - jsIr-runtime
          - jsLegacy-runtime
        All of them match the consumer attributes:
          - Variant 'jsIr-runtime' capability org.jetbrains.kotlinx:kotlinx-datetime:0.1.0:
              - Unmatched attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.jetbrains.kotlin.js.compiler 'ir' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.usage 'kotlin-runtime' and found compatible value 'kotlin-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'js' and found compatible value 'js'.
          - Variant 'jsLegacy-runtime' capability org.jetbrains.kotlinx:kotlinx-datetime:0.1.0:
              - Unmatched attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.jetbrains.kotlin.js.compiler 'legacy' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.usage 'kotlin-runtime' and found compatible value 'kotlin-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'js' and found compatible value 'js'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by ilgonmic** [comment]
kotlinx-datetime published in 2 variants, in `legacy` and `ir` compilers.
And in 1.3.72 gradle plugin is not ready for this situation. So since 1.4.0 it will work smoothly, but before it, it requires workaround
[KT-40226](https://youtrack.jetbrains.com/issue/KT-40226)
