### ISSUE TITLE
Update Kotlin version

### ISSUE THREAD

**Issue by IsakTheHacker** [Kotlin/kotlinx-datetime#355]
Please update the Kotlin version to 1.9.22 for the next release candidate

**Comment by dkhalanskyjb** [comment]
Please explain why. If `kotlinx-datetime` doesn't work on 1.9.22 because we used the older compiler version, there's a problem that we need to solve.

**Comment by IsakTheHacker** [comment]
Oh no issues as far as I know, just thought it would be a good idea since 1.9.22 is the newest

**Comment by dkhalanskyjb** [comment]
We typically don't upgrade to things just because they're the newest. If there are some objective reasons to upgrade (to fix a compilation bug, or to remove an `OptIn` from the API that became stable, or to access some new functionality, and so on), then we do it.
