### ISSUE TITLE
ABI incompatible change on `kotlinx.datetime/LocalDateTime.Companion.parse` function in 0.6.0 release

### ISSUE THREAD

**Issue by StylianosGakis** [Kotlin/kotlinx-datetime#356]
This comes from the discussion here https://slack-chats.kotlinlang.org/t/16634293/trying-out-new-kotlinx-datetime-0-6-0-rc-version-and-getting#44912a7d-4923-4870-96b3-872a2a526992
As noted by Benoit, it looks like this change here https://github.com/Kotlin/kotlinx-datetime/commit/f18cb890e648e5903b4530f3ed8b7d2115dc6679#diff-b1fa2bed442da9d0bb3e4a64b49454763afa5ee6358da76838a8a38654324ca1R174 is what has started producing this crash.
I am not sure if the ABI compatibility is expected to be held with these 0.x versions, but it'd be interesting to hear your thoughts on this.

**Comment by dkhalanskyjb** [comment]
The answer is, the library is experimental, as you noticed, so we make no binary compatibility guarantees. Even for stable libraries, for Native, ensuring binary compatibility is work-in-progress, and as is, is done on a best effort basis (as opposed to the JVM, where we have strict binary compatibility guarantees for stable API).

Here's some code that could potentially fix this: https://github.com/Kotlin/kotlinx-datetime/pull/357 If someone could build our library with this PR and check if the problem disappears, it would be great. Or someone could give us a reproducing project so we could check this ourselves.
