### ISSUE TITLE
Failed requirement on strange time zone

### ISSUE THREAD

**Issue by kunyavskiy** [Kotlin/kotlinx-datetime#359]
Attempt of parsing with following (minimized) format crashes with exception saying "Failed requirement"

```
    val dateTimeFormatter = DateTimeComponents.Format {
        optional {
            offset(UtcOffset.Format {
               offsetHours(Padding.NONE)
               optional { offsetMinutesOfHour(Padding.NONE) }
            })
        }
    }
 ```
 
 It's not very helpful to understand what is wrong.

**Comment by dkhalanskyjb** [comment]
Yes, this exception needs to be improved. A quick answer as to why the exception is thrown: the format is ambiguous. For example, `+111` could be parsed as either `+01:11` or `+11:01`. Our system recognizes this and fails instead of trying to salvage the situation.
