### ISSUE TITLE
How to de/serialize types?

### ISSUE THREAD

**Issue by wellingtoncosta** [Kotlin/kotlinx-datetime#36]
I trying to use this library, and I would like to know how to de/serialize types e.g. `LocalDate`, `LocalDateTime`.

**Comment by ilya-g** [comment]
I'd recommend using [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization/). 
We have plans to provide some ready to use serializers in future.

**Comment by wellingtoncosta** [comment]
Yeah. I'm using kotlinx.serialization, and I found a way to de/serialize the mentioned types by using custom serializers.

**Comment by qrezet** [comment]
hi @wellingtoncosta, can you share your custom serializer for DateTime?

**Comment by wellingtoncosta** [comment]
@qrezet I wrote this custom de/serializer in a private project of my previous company. I'll try to get this piece of code.

**Comment by qrezet** [comment]
@wellingtoncosta Thanks in advance!

**Comment by dkhalanskyjb** [comment]
@qrezet if you need serializers urgently, you may want to have a look at this PR: https://github.com/Kotlin/kotlinx-datetime/pull/101 If everything goes well, they will be available in the next release in some form.

**Comment by qrezet** [comment]
@dkhalanskyjb Awesome! Thanks for the update!

**Comment by qrezet** [comment]
Hi @dkhalanskyjb, if I'm not mistaken, this has already been part of the latest Ktor release right? 1.5.3?

**Comment by dkhalanskyjb** [comment]
Hi @qrezet, not sure what you mean, Ktor is not even integrated with the datetime library. It does have support for serialization but, as far as I know, does not provide any serializers of its own.

Also, the PR was merged, so the serializers for kotlinx-datetime are in the main branch now!
