### ISSUE TITLE
Feature: building instant from DateTimeComponents

### ISSUE THREAD

**Issue by kunyavskiy** [Kotlin/kotlinx-datetime#364]
Whlile doc for DateTimeComponents says it's impossible to construct it on purpose, it looks like it is a convenient way of building Instant or maybe other primitives from it. 

What do you think about add API like following 

```
fun Instant.Companion.fromComponents(block: DateTimeComponents.() -> Unit) : Instant { 
  return DateTimeComponents().apply(block).toInstantUsingOffset()
}
```

Note, that one can already implement it with current public API, but it looks like a hack:
```
fun Instant.Companion.fromComponents(block: DateTimeComponents.() -> Unit) : Instant { 
  return DateTimeComponents.Format{}.parse("").apply(block).toInstantUsingOffset()
}
```

**Comment by dkhalanskyjb** [comment]
Please provide some code that you think is cumbersome to write without `DateTimeComponents` but is easy with it. Maybe we'll figure out a better way.

**Comment by kunyavskiy** [comment]
Basically, the example I had was building an instant from a date manually parsed by regex. 

I've now found, that there is a constructor of LocalDate from components, which I missed and it mostly cover the problem. So probably, probably, the main usecase I have in mind is unfing code between formatting and different `kotlinx.datetime` class construction from some external format, where the only thing you need is an extention function filling DateTimeComponents. 

But that doesn't sound so important.

**Comment by kunyavskiy** [comment]
It's not much useful for LocalDate, because it is basically subset of components. 

While 
```
Instant.fromComponents {
   year = someYear
   month = someMonth
   dayOfMonth = someDayOfMonth
   ...
}
```
makes more sense, as otherwise you would need exponential number of constructor in Instant (e.g. TimeZone vs UtcOffset, month vs monthNumber, year+month+dayOfMonth vs LocalDate).

**Comment by dkhalanskyjb** [comment]
```kotlin
LocalDateTime(someYear, someMonth, someDayOfMonth, someHour, someMinute).toInstant(TimeZone.of("Europe/Berlin"))
LocalDate(someYear, someMonth, someDayOfMonth).atTime(time).toInstant(UtcOffset.ZERO)
```
etc.

**Comment by dkhalanskyjb** [comment]
If there's still some interest in this, please let us know, and we'll reopen the issue.

**Comment by kunyavskiy** [comment]
Well, I argree that the options you suggested above already provides ability of doing what I have described. Although I still think mine are more convenient. But as it is pretty easy to implement it yourself, avoiding API duplication is fine.

**Comment by dkhalanskyjb** [comment]
It's not the API duplication that's the problem but making `DateTimeComponents` anything more than a thing for parsing and formatting. See, it's an unpleasant thing in general: it's mutable, non-thread-safe, people may be tempted to do invalid datetime arithmetic using its fields, etc. We'd rather not give `DateTimeComponents` any more power than it already has.
