### ISSUE TITLE
Support @Serializable

### ISSUE THREAD

**Issue by NorbertSandor** [Kotlin/kotlinx-datetime#37]
kotlinx-serialization should be supported.

**Comment by ilya-g** [comment]
Yes, we have that planned. See also #36.

**Comment by dotCipher** [comment]
Is this open to contributions? I would love to contribute to the project if so!

**Comment by dkhalanskyjb** [comment]
Just a quick heads-up: this is in progress.

**Comment by KevinBassaDevelopment** [comment]
@dkhalanskyjb When do you plan to do the next release? We waited for this feature to complete to use kotlinx-datetime, but unfortunately there are no previews or dev releases to use it already.

**Comment by dkhalanskyjb** [comment]
@KevinBassaDevelopment quite soon; if everything goes well, the new release should happen in early May.
Also, there is a preview version, see https://github.com/Kotlin/kotlinx-datetime/issues/108.
