### ISSUE TITLE
Consider removing `Clock.asTimeSource`

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx-datetime#372]
There are no known public usages of this function: https://grep.app/search?q=asTimeSource&words=true Also, `Clock.System.asTimeSource().measureTime { }` looks fairly benign, even though it doesn't do what you want, given that the system clock can jump in time by several minutes occasionally.

**Comment by dkhalanskyjb** [comment]
What's the purpose of what? `Clock`? It's to show you the current time, according to the system. `2024-03-22T09:43:15Z`, as of writing.

**Comment by hfhbd** [comment]
How is this issue linked to #382?

Also, isn't the (wall) clock based Timesource more precise than the monotonic due to ntp syncs/monotonic pauses, see https://github.com/Kotlin/kotlinx-datetime/pull/164#issuecomment-997859203?

**Comment by dkhalanskyjb** [comment]
> How is this issue linked to https://github.com/Kotlin/kotlinx-datetime/issues/382?

If we decide this function is useful after all, I think that it, too, should migrate to the stdlib.

> Also, isn't the (wall) clock based Timesource more precise than the monotonic due to ntp syncs/monotonic pauses, see https://github.com/Kotlin/kotlinx-datetime/pull/164#issuecomment-997859203?

Wall clocks are neither more nor less precise than `TimeSource.MONOTONIC`, they simply serve different needs and fail in different scenarios.

* `TimeSource.MONOTONIC` measures the elapsed time from the point of view of a program. If we start now, let the program run for a couple of seconds, the time measured by `TimeSource.MONOTONIC` will be two seconds. It won't be `-2` seconds, it won't be `0`. You don't know what the wall clock will say, because someone could have adjusted it in the meantime, or because the computer didn't consider some amount of time due to being hibernated.
* `Clock.System.now()` finds out the current wall-clock time, according to the computer. We could look at the clock now, and two seconds *later* (in terms of the time that actually elapsed), the wall clock could stay the same, or even shift to an earlier time, or whatever, because someone adjusted the clock in the meantime.

**Comment by dalewking** [comment]
Not a public usage of this, but our project uses this for one reason. We have a cache class that is supposed to expire. When we store a value we also store a TimeMark with it to know whether the value has expired. That time mark comes from an object that implements Clock so that we can control time in tests to tests things like the cache expiration.

I think the problem with Monotonic is that it doesn't have a good way to control time in tests. It could probably be made to do so, but I think it is not quite there.

**Comment by dkhalanskyjb** [comment]
> I think the problem with Monotonic is that it doesn't have a good way to control time in tests.

Did you try https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-test-time-source/ ? What's missing from it?

**Comment by hfhbd** [comment]
> I think the problem with Monotonic is that it doesn't have a good way to control time in tests.

What about [TestTimeSource](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-test-time-source/)?

**Comment by ilya-g** [comment]
> That time mark comes from an object that implements Clock so that we can control time in tests to tests things like the cache expiration.

@dalewking However in production, do you use Monotonic time source or the one that is obtained from `Clock.System` as well? I.e. are your timeouts tied to the wall clock time or monotonic time?

**Comment by dalewking** [comment]
> @dalewking However in production, do you use Monotonic time source or the one that is obtained from `Clock.System` as well? I.e. are your cache expiration timeouts tied to the wall clock time or monotonic time?

Just now getting back to this and we were not using Monotonic and now I agree that Clock.asTimeSource should go away.

For a good discussion on the topic see: https://www.youtube.com/watch?v=i1wysckHg2o
