### ISSUE TITLE
[iOS] Fix parsing string without seconds

### ISSUE THREAD

**Issue by romanyczn1** [Kotlin/kotlinx-datetime#375]
On ios im getting an exception when trying to Instant.parse string without seconds "Failed to parse an instant from '2024-04-01T15:30+03:00'" "Position 16: Expected : but got +"

On android it's behave normally

How can i resolve this?

**Comment by dkhalanskyjb** [comment]
Duplicate of https://github.com/Kotlin/kotlinx-datetime/issues/369
You can resolve this by defining a custom format:
```kotlin
val format = DateTimeComponents.Format {
  dateTime(LocalDateTime.Formats.ISO)
  offset(UtcOffset.Formats.ISO)
}
Instant.parse("2024-04-01T15:30+03:00", format)
```
