### ISSUE TITLE
Q: How to parse\format specific string?

### ISSUE THREAD

**Issue by jershell** [Kotlin/kotlinx-datetime#38]
Hi. I have ```DATE_FORMAT_PATTERN2 = "yyyy-MM-dd'T'HH:mm:ss"```. How I can parse it?

**Comment by ilya-g** [comment]
We don't have common formatting and parsing API yet. As a workaround you could rely on the API provided by the platform, e.g. use `java.time` and then convert the parsed value to the corresponding Kotlin type with one of the conversion functions.

But in this particular case your format looks like the ISO-8601 format of `LocalDateTime`, so you can just use `LocalDateTime.parse` function.
