### ISSUE TITLE
Not supported on Android 7.0? What are the minimum supported Android and IOS versions?

### ISSUE THREAD

**Issue by Oyama-Oyama** [Kotlin/kotlinx-datetime#389]
Using it on Android 7.0 will cause a crash

**Comment by dkhalanskyjb** [comment]
https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#using-in-your-projects includes this instruction:

> If you target Android devices running below API 26, you need to use Android Gradle plugin 4.0 or newer and enable [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).

Does this answer your question?

**Comment by Oyama-Oyama** [comment]
> https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#using-in-your-projects includes this instruction:
> 
> > If you target Android devices running below API 26, you need to use Android Gradle plugin 4.0 or newer and enable [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).
> 
> Does this answer your question?

thanks! I was too careless
