### ISSUE TITLE
Missing methods we had before in Java

### ISSUE THREAD

**Issue by Merdin** [Kotlin/kotlinx-datetime#396]
Hi there!

Coming from the Slack channel I wanted to request the following features we had in Java:

- [getDSTSavings()](https://developer.android.com/reference/kotlin/android/icu/util/TimeZone#getdstsavings)
- [getRawOffset()](https://developer.android.com/reference/kotlin/android/icu/util/TimeZone#getrawoffset)

I need those methods to rewrite existing code to KMP, so that I can have the calculation in my backend and release apps for all the platforms I want. [Here is the code of the existing project](https://github.com/abodehq/Pray-Times).

Code snippets of the usage of the method:
```
private fun detectDaylightSaving(): Double {
        val timez: TimeZone = java.util.TimeZone.getDefault()
        val hoursDiff: Double = timez.getDSTSavings().toDouble()
        return hoursDiff
}
```

```
private val timeZone1: Double
        get() {
            val tz: TimeZone = java.util.TimeZone.getDefault()
            val hoursDiff: Double = (tz.getRawOffset() / 1000.0) / 3600
            return hoursDiff
        }
```

**Comment by dkhalanskyjb** [comment]
Do you happen to know why prayer times depend on the standard and DST offsets, by any chance? We can add such functions in theory, but it would be nice to know for certain that this isn't a mistake in the original code.

**Comment by dkhalanskyjb** [comment]
By the way, it looks like all of these functions are *unused*. Am I reading this incorrectly?

**Comment by Merdin** [comment]
Hi @dkhalanskyjb,

All of this is explained at their website [praytimes.org](https://praytimes.org) (for some reason the website doesn't work now). But I think this has to do with the places on earth where the sun doesn't go down(?)

I will try to use it without these methods and see what happens. You can delete the issue for now.
