### ISSUE TITLE
Is KMM still possible for apps that supports SDK 21?

### ISSUE THREAD

**Issue by ArcherEmiya05** [Kotlin/kotlinx-datetime#407]
I am in migration of **Java 8+ APIs Desugar** to **KotlinX DateTime** for an app that supports SDK 21 to 34, upon reading the README.md with the statement below I was confuse.

> If you target Android devices running below API 26, you need to use Android Gradle plugin 4.0 or newer and enable [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).

Isn't Java 8+ APIs Desugar depends on JVM hence cannot be use for KMM project?

**Comment by dkhalanskyjb** [comment]
If you use `kotlinx-datetime` in a KMM project and enable core library desugaring, it will only affect the JVM target. The other targets will use their own implementations in any case, without delegating to the JVM.

**Comment by ArcherEmiya05** [comment]
What if a feature module that supposed to be a platform agnostic depends on KotlinX DateTime? Does it still need to include desugar library or only on the androidApp module? I am planning to adapt this module to be use as shared/common module for a KMM project.

**Comment by dkhalanskyjb** [comment]
Only the application must enable the desugaring. Intermediate modules shouldn't do that.
