### ISSUE TITLE
What is the purpose of specifying TimeZone?

### ISSUE THREAD

**Issue by ArcherEmiya05** [Kotlin/kotlinx-datetime#412]
I am 1 day or hours behind from the device time.

Original code

```
        val dateFormatter = LocalDateTime.Format { // yyyy-MM-dd
            year()
            char('-')
            monthNumber()
            char('-')
            dayOfMonth()
        }

        val now = Clock.System.now()

        val currentDate = now.toLocalDateTime(TimeZone.UTC)

        val currentDateInMilli = currentDate.toInstant(TimeZone.UTC).toEpochMilliseconds()
        val oldestDateInMilli = now.minus(currentDate.year - 2009L, DateTimeUnit.YEAR, TimeZone.UTC).toEpochMilliseconds()
        val previousMonthInMilli = now.minus(1, DateTimeUnit.MONTH, TimeZone.UTC).toEpochMilliseconds()

       // Some processing of currentDateInMilli

       txtView.text = Instant.fromEpochMilliseconds(it).toLocalDateTime(TimeZone.currentSystemDefault()).format(dateFormatter)
```

Attempt with
```
        val dateFormatter = LocalDateTime.Format { // yyyy-MM-dd
            year()
            char('-')
            monthNumber()
            char('-')
            dayOfMonth()
        }

        val now = Clock.System.now()

        val currentDate = now.toLocalDateTime(TimeZone.currentSystemDefault())

        val currentDateInMilli = currentDate.toInstant(TimeZone.currentSystemDefault()).toEpochMilliseconds()
        val oldestDateInMilli = now.minus(currentDate.year - 2009L, DateTimeUnit.YEAR, TimeZone.currentSystemDefault()).toEpochMilliseconds()
        val previousMonthInMilli = now.minus(1, DateTimeUnit.MONTH, TimeZone.currentSystemDefault()).toEpochMilliseconds()

       // Some processing of currentDateInMilli

       txtView.text = Instant.fromEpochMilliseconds(it).toLocalDateTime(TimeZone.currentSystemDefault()).format(dateFormatter)
```

Why is it the two sample behaves the same? I thought by passing `TimeZone.UTC` and `TimeZone.currentSystemDefault())` when converting between `Instant` and `LocalDate` will set some offset based on provided timezone?

======================================================================================

UPDATE: It seems my actual question here is how to make KotlinX DateTime worked with library like Material DatePicker that [requires](https://github.com/material-components/material-components-android/blob/00dc4c6b5af3939418f1c7d1e4c737dc3fb7fd67/docs/components/Picker.md#timezones) Java 8 DateTime API?

It turns out that the MaterialDatePicker uses [UTC time format](https://en.wikipedia.org/wiki/Coordinated_Universal_Time), which means it doesn't contain any Time Zone information. We are getting correct behavior back when using Java 8 DateTime but after updating with KotlinX DateTime it is no longer working and hours behind.

I also tried the three approach [here](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMi4wLjAiLCJwbGF0Zm9ybSI6ImphdmEiLCJhcmdzIjoiIiwibm9uZU1hcmtlcnMiOnRydWUsInRoZW1lIjoiaWRlYSIsImNvZGUiOiIvKipcbiAqIFlvdSBjYW4gZWRpdCwgcnVuLCBhbmQgc2hhcmUgdGhpcyBjb2RlLlxuICogcGxheS5rb3RsaW5sYW5nLm9yZ1xuICovXG5pbXBvcnQgamF2YS50aW1lLkxvY2FsRGF0ZVRpbWVcbmltcG9ydCBqYXZhLnRpbWUuWm9uZU9mZnNldFxuXG5pbXBvcnQga290bGlueC5kYXRldGltZS5DbG9ja1xuaW1wb3J0IGtvdGxpbnguZGF0ZXRpbWUuRGF0ZVRpbWVVbml0XG5pbXBvcnQga290bGlueC5kYXRldGltZS5UaW1lWm9uZVxuaW1wb3J0IGtvdGxpbnguZGF0ZXRpbWUubWludXNcbmltcG9ydCBrb3RsaW54LmRhdGV0aW1lLnRvSW5zdGFudFxuaW1wb3J0IGtvdGxpbnguZGF0ZXRpbWUudG9Mb2NhbERhdGVUaW1lXG5cbmZ1biBtYWluKCkge1xuICAgIFxuICAgIC8vIEphdmEgOCBEYXRlVGltZVxuICAgIGphdmFEYXRlVGltZSgpXG4gICAgXG4gICAgXG4gICAgLy8gS290bGluWCBEYXRlVGltZVxuICAgIGtvdGxpbkRhdGVUaW1lKClcbiAgICBcbiAgICBrb3RsaW5EYXRlVGltZVV0YygpXG59XG5cbmZ1biBqYXZhRGF0ZVRpbWUoKSB7XG4gICAgXG4gICAgdmFsIGN1cnJlbnREYXRlID0gTG9jYWxEYXRlVGltZS5ub3coKS5hdE9mZnNldChab25lT2Zmc2V0LlVUQylcbiAgICB2YWwgY3VycmVudERhdGVJbk1pbGxpID0gY3VycmVudERhdGUudG9JbnN0YW50KCkudG9FcG9jaE1pbGxpKClcbiAgICB2YWwgcHJldmlvdXNNb250aEluTWlsbGkgPSBjdXJyZW50RGF0ZS5taW51c01vbnRocygxKS50b0luc3RhbnQoKS50b0Vwb2NoTWlsbGkoKVxuICAgIFxuICAgIHByaW50bG4oXCJKYXZhOiAkY3VycmVudERhdGVJbk1pbGxpXCIpXG4gICAgcHJpbnRsbihcIkphdmE6ICRwcmV2aW91c01vbnRoSW5NaWxsaVwiKVxuICAgIFxufVxuXG5mdW4ga290bGluRGF0ZVRpbWUoKSB7XG4gICAgXG4gICAgdmFsIG5vdyA9IENsb2NrLlN5c3RlbS5ub3coKVxuICAgIHZhbCBjdXJyZW50RGF0ZSA9IG5vdy50b0xvY2FsRGF0ZVRpbWUoVGltZVpvbmUuY3VycmVudFN5c3RlbURlZmF1bHQoKSlcbiAgICB2YWwgY3VycmVudERhdGVJbk1pbGxpID0gY3VycmVudERhdGUudG9JbnN0YW50KFRpbWVab25lLmN1cnJlbnRTeXN0ZW1EZWZhdWx0KCkpLnRvRXBvY2hNaWxsaXNlY29uZHMoKVxuICAgIHZhbCBwcmV2aW91c01vbnRoSW5NaWxsaSA9IG5vdy5taW51cygxLCBEYXRlVGltZVVuaXQuTU9OVEgsIFRpbWVab25lLmN1cnJlbnRTeXN0ZW1EZWZhdWx0KCkpLnRvRXBvY2hNaWxsaXNlY29uZHMoKVxuICAgIFxuICAgIHByaW50bG4oXCJLb3RsaW4gTG9jYWw6ICRjdXJyZW50RGF0ZUluTWlsbGlcIilcbiAgICBwcmludGxuKFwiS290bGluIExvY2FsOiAkcHJldmlvdXNNb250aEluTWlsbGlcIilcbiAgICBcbn1cblxuZnVuIGtvdGxpbkRhdGVUaW1lVXRjKCkge1xuICAgIFxuICAgIHZhbCBub3cgPSBDbG9jay5TeXN0ZW0ubm93KClcbiAgICB2YWwgY3VycmVudERhdGUgPSBub3cudG9Mb2NhbERhdGVUaW1lKFRpbWVab25lLlVUQylcbiAgICB2YWwgY3VycmVudERhdGVJbk1pbGxpID0gY3VycmVudERhdGUudG9JbnN0YW50KFRpbWVab25lLlVUQykudG9FcG9jaE1pbGxpc2Vjb25kcygpXG4gICAgdmFsIHByZXZpb3VzTW9udGhJbk1pbGxpID0gbm93Lm1pbnVzKDEsIERhdGVUaW1lVW5pdC5NT05USCwgVGltZVpvbmUuVVRDKS50b0Vwb2NoTWlsbGlzZWNvbmRzKClcbiAgICBcbiAgICBwcmludGxuKFwiS290bGluIFVUQzogJGN1cnJlbnREYXRlSW5NaWxsaVwiKVxuICAgIHByaW50bG4oXCJLb3RsaW4gVVRDOiAkcHJldmlvdXNNb250aEluTWlsbGlcIilcbiAgICBcbn0ifQ==) and they behave all the same yet on the UI level they behave differently.

**Comment by dkhalanskyjb** [comment]
Let's break down your original code.

```kotlin
        val dateFormatter = LocalDateTime.Format { // yyyy-MM-dd
            year()
            char('-')
            monthNumber()
            char('-')
            dayOfMonth()
        }
```

This is actually just `LocalDateTime.Format { date(LocalDate.Formats.ISO) }`.

```kotlin
        val now = Clock.System.now()
```

Here, you take the current moment. The one that happens right now.

```kotlin
        val currentDate = now.toLocalDateTime(TimeZone.UTC)
```

Here, you create a collection of fields—year, month, day, hour, minute, second—that the people in the *Greenwich time zone* see right now.

```kotlin
        val currentDateInMilli = currentDate.toInstant(TimeZone.UTC).toEpochMilliseconds()
```

Here, you convert `currentDate` back to `now`. Basically, you're asking: "What real moment corresponds to the point when the people in the Greenwich time zone observed these year, month, day, hour, minute, and second?" But that moment is just `now` (if there are no DST transitions, and for UTC, there aren't). This can be replaced with just `now..toEpochMilliseconds()`. In any case, `currentDateInMilli` is unused in the sample, so we can remove it.

```kotlin
        val oldestDateInMilli = now.minus(currentDate.year - 2009L, DateTimeUnit.YEAR, TimeZone.UTC).toEpochMilliseconds()
        val previousMonthInMilli = now.minus(1, DateTimeUnit.MONTH, TimeZone.UTC).toEpochMilliseconds()
```

Also seems irrelevant to the sample.

```kotlin
       // Some processing of currentDateInMilli

       txtView.text = Instant.fromEpochMilliseconds(it).toLocalDateTime(TimeZone.currentSystemDefault()).format(dateFormatter)
```

I don't know what's "it," so the example won't run as is, and you didn't explain what "it" is, so I can't help you with this code, sorry.

---

Now, let's look at the three approaches you've tried in Kotlinlang. They *do not* behave the same: the reason you see them behaving the same is that the timezone of play.kotlinlang.org is TimeZone.UTC. Running this in `Europe/Berlin`, I see

```
Java: 1721649261042
Java: 1719057261042
Kotlin Local: 1721642061047
Kotlin Local: 1719050061047
Kotlin UTC: 1721642061056
Kotlin UTC: 1719050061056
```
The numbers are clearly different between Java and Kotlin.

Here's what's going on in `javaDateTime`:

```kotlin
        val currentDate = LocalDateTime.now().atOffset(ZoneOffset.UTC)
        val currentDateInMilli = currentDate.toInstant().toEpochMilli()
        val previousMonthInMilli = currentDate.minusMonths(1).toInstant().toEpochMilli()
```

`LocalDateTime.now()` is equivalent to Kotlin's `Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())` and obtains the year, month, day, hour, minute, and second according to the clocks in the current time zone.

`atOffset(ZoneOffset.UTC)` then pretends that the `LocalDateTime` in the local time zone was actually in the UTC time zone and asks to perform all further arithmetics in `UTC`. It's not true, but that's what the code says.

So, the equivalent code in kotlinx-datetime is:

```kotlin
        val currentDate = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())
        val currentDateInMilli = currentDate.toInstant(TimeZone.UTC).toEpochMilliseconds()
        val previousMonthInMilli = currentDate.toInstant(TimeZone.UTC).minus(1, DateTimeUnit.MONTH, TimeZone.UTC).toEpochMilliseconds()
```

Does this answer your question?

**Comment by ArcherEmiya05** [comment]
> Let's break down your original code.
> 
> ```kotlin
>         val dateFormatter = LocalDateTime.Format { // yyyy-MM-dd
>             year()
>             char('-')
>             monthNumber()
>             char('-')
>             dayOfMonth()
>         }
> ```
> 
> This is actually just `LocalDateTime.Format { date(LocalDate.Formats.ISO) }`.
> 
> ```kotlin
>         val now = Clock.System.now()
> ```
> 
> Here, you take the current moment. The one that happens right now.
> 
> ```kotlin
>         val currentDate = now.toLocalDateTime(TimeZone.UTC)
> ```
> 
> Here, you create a collection of fields—year, month, day, hour, minute, second—that the people in the _Greenwich time zone_ see right now.
> 
> ```kotlin
>         val currentDateInMilli = currentDate.toInstant(TimeZone.UTC).toEpochMilliseconds()
> ```
> 
> Here, you convert `currentDate` back to `now`. Basically, you're asking: "What real moment corresponds to the point when the people in the Greenwich time zone observed these year, month, day, hour, minute, and second?" But that moment is just `now` (if there are no DST transitions, and for UTC, there aren't). This can be replaced with just `now..toEpochMilliseconds()`. In any case, `currentDateInMilli` is unused in the sample, so we can remove it.
> 
> ```kotlin
>         val oldestDateInMilli = now.minus(currentDate.year - 2009L, DateTimeUnit.YEAR, TimeZone.UTC).toEpochMilliseconds()
>         val previousMonthInMilli = now.minus(1, DateTimeUnit.MONTH, TimeZone.UTC).toEpochMilliseconds()
> ```
> 
> Also seems irrelevant to the sample.
> 
> ```kotlin
>        // Some processing of currentDateInMilli
> 
>        txtView.text = Instant.fromEpochMilliseconds(it).toLocalDateTime(TimeZone.currentSystemDefault()).format(dateFormatter)
> ```
> 
> I don't know what's "it," so the example won't run as is, and you didn't explain what "it" is, so I can't help you with this code, sorry.
> 
> Now, let's look at the three approaches you've tried in Kotlinlang. They _do not_ behave the same: the reason you see them behaving the same is that the timezone of play.kotlinlang.org is TimeZone.UTC. Running this in `Europe/Berlin`, I see
> 
> ```
> Java: 1721649261042
> Java: 1719057261042
> Kotlin Local: 1721642061047
> Kotlin Local: 1719050061047
> Kotlin UTC: 1721642061056
> Kotlin UTC: 1719050061056
> ```
> 
> The numbers are clearly different between Java and Kotlin.
> 
> Here's what's going on in `javaDateTime`:
> 
> ```kotlin
>         val currentDate = LocalDateTime.now().atOffset(ZoneOffset.UTC)
>         val currentDateInMilli = currentDate.toInstant().toEpochMilli()
>         val previousMonthInMilli = currentDate.minusMonths(1).toInstant().toEpochMilli()
> ```
> 
> `LocalDateTime.now()` is equivalent to Kotlin's `Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())` and obtains the year, month, day, hour, minute, and second according to the clocks in the current time zone.
> 
> `atOffset(ZoneOffset.UTC)` then pretends that the `LocalDateTime` in the local time zone was actually in the UTC time zone and asks to perform all further arithmetics in `UTC`. It's not true, but that's what the code says.
> 
> So, the equivalent code in kotlinx-datetime is:
> 
> ```kotlin
>         val currentDate = Clock.System.now().toLocalDateTime(TimeZone.currentSystemDefault())
>         val currentDateInMilli = currentDate.toInstant(TimeZone.UTC).toEpochMilliseconds()
>         val previousMonthInMilli = currentDate.toInstant(TimeZone.UTC).minus(1, DateTimeUnit.MONTH, TimeZone.UTC).toEpochMilliseconds()
> ```
> 
> Does this answer your question?

Yes thanks a lot, now I understand the issue as I should be using `currentDate` for `currentDateInMilli` and `previousMonthInMilli`.

As for the sample where you are looking for `it` in `Instant.fromEpochMilliseconds(it).toLocalDateTime(TimeZone.currentSystemDefault()).format(dateFormatter)`, it supposed to be the `selection` property from MaterialDatePicker which is the problematic part. Anyway thanks again!
