### ISSUE TITLE
Add a dayOfYear option

### ISSUE THREAD

**Issue by tylerwilson** [Kotlin/kotlinx-datetime#414]
I need to parse / construct a Julian date, which requires the day of year value. It would fall in nicely with the dayOfMonth and dayOfWeek values. :-) 

Or, is there a way I can construct my own WithDate extension that would allow me to add it on my end?

**Comment by dkhalanskyjb** [comment]
> I need to parse / construct a Julian date

Which is it? You can construct the value (though the API isn't nice) today:

```kotlin
LocalDate(year, 1, 1).plus(dayOfYear - 1, DateTimeUnit.DAY)
```

Parsing, on the other hand, is only available via dirty hacks.

**Comment by tylerwilson** [comment]
It is actually for parsing. I have a date time in the format of "yyDDDHHmm". I have been using the format helpers to do most of my parsing thus far. Perhaps the string based version might handle this? 

Is this - dayOfYear - something we think could make it in a future version?
