### ISSUE TITLE
Crash - Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by kostapostolakis** [Kotlin/kotlinx-datetime#418]
I use in shared file the following to get the milliseconds, but I see some crashes in Firebase.

Clock.System.now().toEpochMilliseconds()

This is happening only in Android 7.

Can someone help me to resolve the crash?

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/6aa91e88-58a2-417e-b30d-a69c76bd79f8">

**Comment by dkhalanskyjb** [comment]
https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#using-in-your-projects

> If you target Android devices running below API 26, you need to use Android Gradle plugin 4.0 or newer and enable [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).
