### ISSUE TITLE
Plus an minus methods on `LocalTime` and `LocalDateTime` types

### ISSUE THREAD

**Issue by nesk** [Kotlin/kotlinx-datetime#429]
The `Instant` type supports [addition](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/plus.html) and [subtraction](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/-instant/minus.html) of a `Duration`:

```kotlin
fun example(now: Instant) {
    now - 5.seconds
    now + 5.seconds
}
```

The `LocalDate` type supports [addition](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/plus.html) and [subtraction](https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime/minus.html) of `DatePeriod`:

```kotlin
fun example(now: LocalDate) {
    now - DatePeriod(days = 2)
    now + DatePeriod(days = 2)
}
```

However, the `LocalTime` doesn't support any addition or subtraction, which requires cumbersome code to do these changes:

```kotlin
fun example(now: LocalTime) {
    LocalTime.fromSecondOfDay(now.toSecondOfDay() - 5)
    LocalTime.fromSecondOfDay(now.toSecondOfDay() + 5)
}
```

What about adding a `TimePeriod` type? This would allow to write code like this:

```kotlin
fun example(now: LocalTime) {
    now - TimePeriod(seconds = 5)
    now + TimePeriod(seconds = 5)
}
```

This would also pave the way for addition and subtraction of the `LocalDateTime` type:

```kotlin
fun example(now: LocalDateTime) {
    now - DateTimePeriod(days = 2, seconds = 5)
    now + DateTimePeriod(days = 2, seconds = 5)
}
```

**Comment by dkhalanskyjb** [comment]
Please read https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#date--time-arithmetic

If you have some specific code that needs `LocalTime` arithmetics, please share it here or on the Kotlin Slack, and we'll help you reach an idiomatic and robust solution.
