### ISSUE TITLE
Clock.System.now() on Android API 24

### ISSUE THREAD

**Issue by aaf-dev** [Kotlin/kotlinx-datetime#43]
Hello!
How can I get the current system time on an Andoid device with API lower than 26 using this library?
When i use `localDateTime.month.getDisplayName()` I get a warning that the call requires API level 26, but with `Clock.System.now ()` there is no warning

**Comment by JakeWharton** [comment]
You must enable core library desugaring which will make the `java.time` APIs available on older versions of Android. More info at https://developer.android.com/studio/write/java8-support#library-desugaring.

**Comment by aaf-dev** [comment]
Thanks!
