### ISSUE TITLE
Add conversion extension properties also to unsigned types

### ISSUE THREAD

**Issue by kejml** [Kotlin/kotlinx-datetime#451]
I like using existing `Int.hours`, `Double.hours` and `Long.seconds` extension properties.

Could we also get the same for unsigned types, i.e. `UInt.hours` and `ULong.seconds`?

**Comment by dkhalanskyjb** [comment]
Hi! You are probably talking about `kotlin.time.Duration`, right? This is `kotlinx.datetime`, a different library. Filed at https://youtrack.jetbrains.com/issue/KT-72487/Add-extensions-like-UInt.hours-to-Duration

**Comment by kejml** [comment]
Oh yes, I'm sorry, thanks for point me in the correct direction
