### ISSUE TITLE
Consider adding `formatOrNull`

### ISSUE THREAD

**Issue by ThomasETN** [Kotlin/kotlinx-datetime#452]
As title, i.e.
```kotlin
fun LocalDate.formatOrNull(dateTimeFormat: DateTimeFormat<LocalDate>) = runCatching { this.format(dateTimeFormat) }.getOrNull()
```

(version 0.6.1)

**Comment by dkhalanskyjb** [comment]
Hi @ThomasETN! Please provide an example where this function could be useful.

**Comment by ThomasETN** [comment]
I suppose it should be useful in all use-sites where the existing function `LocalDate.format(format: DateTimeFormat<LocalDate>)` may be called, because the undery function `DateTimeFormat.format` could throw `IllegalArgumentException`

**Comment by dkhalanskyjb** [comment]
`DateTimeFormat.format` only throws exceptions if the format requests any data that's not present in the object, like `DateTimeComponents.Format { hour() }.format { year = 2024 }`. `LocalDate` has everything `DateTimeFormat<LocalDate>` can need. If `DateTimeFormat<LocalDate>.format` throws for a `LocalDate`, either it's a bug in our implementation or something like `StackOverflowException` or `OutOfMemoryError`, something that can happen in any function.

**Comment by ThomasETN** [comment]
I understand now, sorry for opening the issue
