### ISSUE TITLE
Eastern Daylight Time (`EDT`) not recongnized by `TimeZone.of`

### ISSUE THREAD

**Issue by ThomasETN** [Kotlin/kotlinx-datetime#455]
(Version `0.6.1`, Android)

As title, `TimeZone.of("EDT")` throws `IllegalTimeZoneExcception`.

***
[Eastern Time Zone - Wikipedia](https://en.wikipedia.org/wiki/Eastern_Time_Zone)

**Comment by dkhalanskyjb** [comment]
Yes, that's expected. We intentionally don't support such short identifiers, with some exceptions. From https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations :

> [Time zones](https://en.wikipedia.org/wiki/Time_zone) are often represented by alphabetic abbreviations such as "EST", "WST", and "CST", but **these are not part of the international time and date standard** [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) and **their use as sole designator for a time zone is discouraged**.
