### ISSUE TITLE
Locale for JS not working?

### ISSUE THREAD

**Issue by alekseyHunter** [Kotlin/kotlinx-datetime#456]
Hello!

I'm trying to format LocalDateTime with next pattern "dd MMMM": 
```
actual fun LocalDateTime.format(format: String): String {
    return DateTimeFormatter.ofPattern(format)
        .withLocale("ru" as Locale)
        .format(
            nativeJs(
                Date(
                    milliseconds = this.toInstant(
                        TimeZone.currentSystemDefault()
                    ).toEpochMilliseconds()
                )
            )
        )
}
```

I got the next error:
![image](https://github.com/user-attachments/assets/7e7a3e65-eaec-493a-b566-3b7e678e2212)

**Comment by dkhalanskyjb** [comment]
Hi! `DateTimeFormatter`, `withLocale`, `Locale`, `nativeJs`, and `Date` are not parts of this library at all, so we can't help you with that.

Our own implementation of formatting also currently doesn't support locales: https://github.com/Kotlin/kotlinx-datetime/issues/352
