### ISSUE TITLE
iOS crashing

### ISSUE THREAD

**Issue by harsh2342** [Kotlin/kotlinx-datetime#463]
With kotlin 2.0.20 and compose 1.7.1 datepicker is not working in iOS and desktop
**Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError: Function 'rememberSnapFlingBehavior' can not be called: No function found for symbol 'androidx.compose.foundation.gestures.snapping/rememberSnapFlingBehavior|rememberSnapFlingBehavior(androidx.compose.foundation.lazy.LazyListState;androidx.compose.runtime.Composer?;kotlin.Int){}[0]'**

In android and web it is working fine.

**Comment by dkhalanskyjb** [comment]
Hi! Sorry, but `rememberSnapFlingBehavior`, or `androidx.compose` are completely unrelated to this library. This is `kotlinx-datetime`, we are developing classes like `LocalDate`, `Instant`, and `TimeZone` here.
