### ISSUE TITLE
Question: About the two-symbol year ("yy")

### ISSUE THREAD

**Issue by frist008** [Kotlin/kotlinx-datetime#464]
Hi everyone, I can't find proper documentation on how I can get the following pattern:

➡️**Wen, Feb 93**

I'm expecting the next api but it's not there:
```kotlin
    private val CALENDAR_FORMATTER: DateTimeFormat<LocalDate> by lazy {
        LocalDate.Format {
            dayOfWeek(DayOfWeekNames.ENGLISH_ABBREVIATED)
            chars(", ")
            monthName(MonthNames.ENGLISH_ABBREVIATED)
            char(' ')
            year(YearDigits.TWO)
        }
    }
```

I see that I can use `DateTimeComponents.Format` -> `DateTimeFormat<DateTimeComponents>` with `byUnicodePattern()`.

BUT I get the time in milliseconds

```kotlin
    public fun fromCalendarMs(timeMs: Long): String =
        LocalDate
            .fromEpochDays(timeMs.milliseconds.inWholeDays.toInt())
            .format(CALENDAR_FORMATTER)
```

Function format does not support DateTimeFormat<DateTimeComponents>

**Comment by dkhalanskyjb** [comment]
1. There's no such thing as "`YearDigits.TWO`" in any of the APIs that I know of. What we have is a `yearTwoDigits` function. See https://kotlinlang.org/api/kotlinx-datetime/kotlinx-datetime/kotlinx.datetime.format/-date-time-format-builder/-with-date/ for a full list of date-based directives.
2. You can use `byUnicodePattern` not just with `DateTimeComponents.Format` but actually in any format builder. For example, `LocalDate.Format { byUnicodePattern("yy") }` would work. It's not advised to use `byUnicodePattern`, though; if you call `println(DateTimeFormat.formatAsKotlinBuilderDsl(LocalDate.Format { byUnicodePattern("yy") }))`, you'll see how the same can be written without Unicode formats (that is, with `yearTwoDigits`).
3. If `CALENDAR_FORMATTER` is `DateTimeFormat<DateTimeComponents>`, you can use it like this to format a local date: `CALENDAR_FORMATTER.format { setDate(yourLocalDate) }`.
4. Note that `timeMs.milliseconds.inWholeDays.toInt()` will not work correctly in time zones other than fixed-offset ones (like UTC).

Overall, https://github.com/Kotlin/kotlinx-datetime/blob/master/README.md should provide a good starting point for getting familiar with the general shape of `kotlinx-datetime` API.
