### ISSUE TITLE
Alternative JVM implementation for Android

### ISSUE THREAD

**Issue by olegivo** [Kotlin/kotlinx-datetime#53]
From plans (in readme.md):
>An alternative JVM implementation for Android might be needed.

Current JVM implementation (based on JodaTime) have some cons, that can be avoided by using, for example, [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP).
1. [Why not use ThreeTenBP?](https://github.com/JakeWharton/ThreeTenABP#why-not-use-threetenbp)
Similar to the problems with using [Joda-Time on Android](https://github.com/dlew/joda-time-android#why-this-library), the [threetenbp](https://github.com/ThreeTen/threetenbp) uses a JAR resource for loading timezone information. This is an extremely [inefficient mechanism on Android](http://blog.danlew.net/2013/08/20/joda_time_s_memory_issue_in_android/).
This library places the timezone information as a standard Android asset and provides a custom loader for parsing it efficiently.
1. [Why not use Joda-Time?](https://github.com/JakeWharton/ThreeTenABP#why-not-use-joda-time)
Joda-Time has a very large API which brings with it a very large binary size and large method count. The creator of both JSR-310 and Joda-Time has also said that while Joda-Time isn't broken, it does have [design flaws](http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html).
If you are using Joda-Time already, there's little reason to switch unless its size or method count is relevant to you. For new projects, however, this library offers the standard APIs in Java 8 as a much smaller package in not only binary size and method count, but also in API size.

**Comment by JakeWharton** [comment]
> have some cons, that can be avoided by using, for example, ThreeTenABP.

What cons? ThreeTenABP is just a repackaging of ThreeTenBP which is a less efficient version java.time before it was merged into the JDK. Bugs which are fixed in the JDK in java.time are rarely fixed in ThreeTenBP because of the differing licenses.

With core library desugaring being available for Android now, there should be no reason to use ThreeTenBP or ThreeTenABP anymore.

**Comment by olegivo** [comment]
You are right, I forgot about desugaring
