### ISSUE TITLE
Clock.System.now() crashes on Android 4.1 (API 16)

### ISSUE THREAD

**Issue by softartdev** [Kotlin/kotlinx-datetime#54]
When calling the method `Clock.System.now()` on old Android 4.1 Jelly Bean (API 16) device/emulator the app throw `java.lang.ExceptionInInitializerError`:
```
09-21 13:13:27.111 2965-3003/com.softartdev.noteroom E/BaseViewModel$launch: java.lang.ExceptionInInitializerError
        at kotlinx.datetime.Clock$System.now(Clock.kt:17)
```
On the last Android versions works fine, checked on API 26~30.
The problem can be reproduce from source code of [my pet-project](https://github.com/softartdev/NoteDelight/blob/ec7b0fc2669919169493d5a6fcbcf944c066a83f/shared/src/commonMain/kotlin/com/softartdev/notedelight/shared/date/platformDate.kt#L10):
```
fun createLocalDateTime(): LocalDateTime = Clock.System.now()
    .toLocalDateTime(TimeZone.currentSystemDefault())
```

**Comment by ilya-g** [comment]
See this reply: https://github.com/Kotlin/kotlinx-datetime/issues/48#issuecomment-687264154

> you need to use AGP 4.0 or newer and enable core library desugaring: https://developer.android.com/studio/write/java8-support#library-desugaring

**Comment by softartdev** [comment]
Thank you, problem solved!
