### ISSUE TITLE
Support custom formats (for parsing as well as toString operations)

### ISSUE THREAD

**Issue by fkrauthan** [Kotlin/kotlinx-datetime#58]
I think one of the biggest missing items is a formatting system to parse custom date formats as well as to serialize a date object back to a string with custom format. When working with dates both directions are very important and common.

**Comment by tadfisher** [comment]
A replacement (or delegate) for the ICU RelativeDateTimeFormatter would be a useful addition. The use case is to format localized absolute times, e.g. "today", "yesterday", and "last week".

**Comment by tylerwilson** [comment]
Hope this is being worked on. I would love to use this package cross-platform, but not having a generic formatting/parsing system is holding us back. Thanks.

**Comment by Artrosis** [comment]
I needed formatting for logs
