### ISSUE TITLE
Could not find org.jetbrains.kotlinx:kotlinx-datetime:0.1.0 (in default repositories)

### ISSUE THREAD

**Issue by ln-12** [Kotlin/kotlinx-datetime#61]
I wanna run a Kotlin Multiplatform Mobile project using this library. After configuring the gradle script like shown in the screenshot, I get the following error:

```
Execution failed for task ':androidApp:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':androidApp:debugRuntimeClasspath'.
   > Could not find org.jetbrains.kotlinx:kotlinx-datetime:0.1.0.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.0/kotlinx-datetime-0.1.0.pom
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.0/kotlinx-datetime-0.1.0.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-datetime/0.1.0/kotlinx-datetime-0.1.0.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.0/kotlinx-datetime-0.1.0.pom
     Required by:
         project :androidApp > project :shared

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Only after adding the custom maven repo to the build gradle file inside the android sub project, the dependency is found. I don't think that this is right.

![image](https://user-images.githubusercontent.com/36760115/96845097-9aae8580-1450-11eb-9f77-d1fc8921ab8f.png)

**Comment by JakeWharton** [comment]
It is what the docs instruct you to do, yes: https://github.com/Kotlin/kotlinx-datetime#using-in-your-projects

**Comment by ln-12** [comment]
Well, I don't think that this makes sense. The KMM project is a library itself from the android apps point of view. So why should the app know about the dependency source of the library?

**Comment by NikolaGrujic91** [comment]
I am experiencing the same issue by following instructions from the README. Event the workaround proposed by @ln-12 is not working for me

![Screenshot 2020-10-24 at 08 18 23](https://user-images.githubusercontent.com/17230877/97069600-ae352a00-15d1-11eb-82eb-a4691840e957.png)
![Screenshot 2020-10-24 at 08 18 44](https://user-images.githubusercontent.com/17230877/97069609-b55c3800-15d1-11eb-9d75-18bcfb59dd89.png)

**Comment by dogan-gulcan-zocdoc** [comment]
@NikolaGrujic91 the logs indicate that the `app` module is unable to find the binaries. You can try adding `maven(url = "https://kotlin.bintray.com/kotlinx/")` into your `app:gradle` repositories, then it should work.

**Comment by TiferetCohenZemingo** [comment]
I'm experiencing the same issues. @dogan-gulcan-zocdoc suggestion did work, but it puts me in another difficult position: I'm writing an SDK, which means I need to make sure users that will use it should add it as well. I hope there will be another solution soon.
