### ISSUE TITLE
"You'll have to keep track of the TimeZone of the scheduled event separately"

### ISSUE THREAD

**Issue by sboishtyan** [Kotlin/kotlinx-datetime#65]
Sorry, but what a problem to create a type that will hold LocalDateTime and TimeZone?
Now I create my own Type and I consider every developer who needs a date, time, and time zone will create

**Comment by elizarov** [comment]
This is a very niche need.  Relatively few applications (mostly calendar-type apps) schedule events in different timezones and would need this kind of LocalDateTime+TimeZone type. It is Ok for those applications to define their own types for that purpose. We don't want to complicate the API for everybody else.
