### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by jsdeyro** [Kotlin/kotlinx-datetime#69]
LocalDateTime is only compatible for API 26 >. Does this support lower version of API < 26?

**Comment by shiSHARK** [comment]
I have the same issue.

**Comment by JakeWharton** [comment]
Yes. You must enable core library desugaring. See https://github.com/Kotlin/kotlinx-datetime/issues/48#issuecomment-687264154

**Comment by ilya-g** [comment]
I've added a comment about enabling library desugaring in ReadMe.
