### ISSUE TITLE
[JS] DateTimeException: unsupported ZoneId: Europe/Berlin

### ISSUE THREAD

**Issue by fluidsonic** [Kotlin/kotlinx-datetime#71]
From the README:
```kotlin
val tzBerlin = TimeZone.of("Europe/Berlin")
```

Result in Kotlin/JS:
> IllegalTimeZoneException {message: "DateTimeException: unsupported ZoneId:Europe/Berlin", cause: JsJodaException, name: "IllegalTimeZoneException", stack: "DateTimeException: unsupported ZoneId:Europe/Berlin …"}

Either there's a bug or the documentation lacks some info about how to use time zones. I guess `js-joda-timezone` is needed.

**Comment by ilya-g** [comment]
Yes, we add timezone module in JS tests in the following way:  https://github.com/Kotlin/kotlinx-datetime/blob/master/core/jsTest/src/JsJodaTimeZoneModule.kt
