### ISSUE TITLE
Useful internal functions: isLeapYear and monthLength

### ISSUE THREAD

**Issue by lammertw** [Kotlin/kotlinx-datetime#74]
Currently the `isLeapYear` and `Int.monthLength` functions are internal. It would be useful to have these functions publicly available.

**Comment by dkhalanskyjb** [comment]
We did think about it, but couldn't find enough use cases. Could you provide yours?

**Comment by lammertw** [comment]
Sure. In one instance we have a monthly budget of say $100. And on day 10 of the month we have an actual usage cost of $30. We want to know if the user is ahead of budget or not. So we calculate the budget to date using 10 divided by the **number of days in the current month** multiplied by the budget. So we need to know the number of days in the current month.

Another case is were we need to get the last day of the month. For that we use this:
```
fun Month.days(year: Int) = number.monthLength(isLeapYear(year))
val LocalDate.atEndOfMonth get() = LocalDate(year, month, month.days(year))
```

**Comment by dkhalanskyjb** [comment]
Thank you!

We actually want do discourage using such direct computations on datetime, as it is ridiculously easy to get off-by-one errors this way and still get plausible results that are slightly wrong. We are researching which useful functions we could provide that would replace the majority of such calculations with easy-to-follow and robust logic.

You do raise a good point about needing to extrapolate partial data to a whole month. Still, maybe this could be done slightly differently?

```kotlin
/**
 * Returns this date with another day of month.
 *
 * @throws IllegalArgumentException if the resulting date is invalid or exceeds the platform-specific boundary.
 */
fun LocalDate.withDayOfMonth(dayOfMonth: Int) = LocalDate(this.year, this.month, dayOfMonth)

/**
 * The beginning of the next month.
 */
val LocalDate.nextMonth
    get() = withDayOfMonth(1).plus(1, DateTimeUnit.MONTH)

/**
 * The estimated monthly cost.
 *
 * The budget is calculated assuming that the service will be used at the same rate as it was until now,
 * given that the user has spent [currentSpending] from the start of this month up to the start of [currentDate]
 * (non-inclusive).
 *
 * [currentDate] can't be the first day of the month.
 */
fun estimatedMonthlyCost(currentDate: LocalDate, currentSpending: Double): Double {
    require(currentDate.dayOfMonth != 1)
    val startOfMonth = currentDate.withDayOfMonth(1)
    val daysInKnownPeriod = startOfMonth.until(currentDate, DateTimeUnit.DAY)
    val costPerDay = currentSpending / daysInKnownPeriod
    val daysInUnknownPeriod = currentDate.until(currentDate.nextMonth, DateTimeUnit.DAY)
    return costPerDay * daysInUnknownPeriod + currentSpending
}
```

I agree that this is more verbose (though it could be written more compactly if needed), but arguably it's also more clear and, more importantly, avoids arithmetic on plain numbers: "Uh, day-of-month numbers are 1-based, so at the start of the 10th day... what, 10 days have passed? That's not right: at the start of the 1st day no days have passed. So, at the start of the 10th day only nine days have passed. Ok. So on average the spending was `currentCost / (currentDate.dayOfMonth - 1)`". While in your particular use case absolute correctness does not even matter and this is a rough estimate anyway, I think discouraging unsafe APIs is worth it in the common case where errors in datetime handling are obscure and yet important.

About the last day of the month: with `nextMonth` as defined above, it can be written with no manual handling of leap years and such like so:
```kotlin
val LocalDate.atEndOfMonth get() = nextMonth - DatePeriod(days = 1)
```

What do you think?

**Comment by lammertw** [comment]
Thank you for the detailed answer. We'll use the proposed `atEndOfMonth` function.

**Comment by mpierucci** [comment]
What is the rationale of exposing a public function such as :
```
    public int length(boolean leapYear) {
        switch (this) {
            case FEBRUARY:
                return (leapYear ? 29 : 28);
            case APRIL:
            case JUNE:
            case SEPTEMBER:
            case NOVEMBER:
                return 30;
            default:
                return 31;
        }
    }
```
If a method to know if isLeapYear is no exposed. Would not be better to internally call the isLeap function then? 
Legit Q

**Comment by dkhalanskyjb** [comment]
@mpierucci, we don't expose such a function. You're probably looking at the JVM's https://docs.oracle.com/javase/8/docs/api/java/time/Month.html.

**Comment by joffrey-bion** [comment]
@dkhalanskyjb Another use case: I would need `isLeapYear` to implement properly some [Day count conventions](https://en.wikipedia.org/wiki/Day_count_convention), such as `Actual/Actual ISDA`.

We could argue that standard day count conventions could be part of Kotlinx Datetime, but it seems a bit too specific for this library, so we might need some primitives to implement it externally without reinventing the wheel for leap years for instance.
