### ISSUE TITLE
Can't download the dependency

### ISSUE THREAD

**Issue by dbikic** [Kotlin/kotlinx-datetime#76]
When I add the dependency to my KMM app, sync the project and run the app, I get the following error message:
```
Execution failed for task ':androidApp:checkXXXDebugAarMetadata'.
> Could not resolve all files for configuration ':androidApp:XXXDebugRuntimeClasspath'.
   > Could not find org.jetbrains.kotlinx:kotlinx-datetime:0.1.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
     Required by:
         project :androidApp > project :shared

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by shpp-vsmaga** [comment]
I have the same problem((

**Comment by shpp-vsmaga** [comment]
> When I add the dependency to my KMM app, sync the project and run the app, I get the following error message:
> 
> ```
> Execution failed for task ':androidApp:checkXXXDebugAarMetadata'.
> > Could not resolve all files for configuration ':androidApp:XXXDebugRuntimeClasspath'.
>    > Could not find org.jetbrains.kotlinx:kotlinx-datetime:0.1.1.
>      Searched in the following locations:
>        - https://plugins.gradle.org/m2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
>        - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
>        - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
>        - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-datetime/0.1.1/kotlinx-datetime-0.1.1.pom
>      Required by:
>          project :androidApp > project :shared
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> ```

Fixed - you should add repository to all projects like:
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven("https://kotlin.bintray.com/kotlinx/")

**Comment by dbikic** [comment]
@shpp-vsmaga awesome, thanks a lot, it solved my issue!

However, I think the setup guide in this repo should be changed. I'm following the official KMM sample app and there is no `allprojects` block in the root `build.gradle` file: https://github.com/Kotlin/kmm-sample/blob/master/build.gradle.kts
