### ISSUE TITLE
KDoc references internal class DateTimeFormatException

### ISSUE THREAD

**Issue by fluidsonic** [Kotlin/kotlinx-datetime#85]
https://github.com/Kotlin/kotlinx-datetime/blob/3af71d2e874592fc70282de441a09d024dcefb54/core/common/src/LocalDateTime.kt#L116

https://github.com/Kotlin/kotlinx-datetime/blob/3af71d2e874592fc70282de441a09d024dcefb54/core/common/src/Exceptions.kt#L22

**Comment by dkhalanskyjb** [comment]
Thanks! There's now a PR for this: https://github.com/Kotlin/kotlinx-datetime/pull/87
