### ISSUE TITLE
Provide construction and/or parsing for ZoneOffset

### ISSUE THREAD

**Issue by cromefire** [Kotlin/kotlinx-datetime#91]
Currently you are not able to directly parse strings like `+02:00` into an `ZoneOffset`. You can do so via
```kotlin
TimeZone.of("+02:00").offsetAt(Instant.fromEpochMilliseconds(0))
```
but it's rather a workaround, than a real solution (and if that's important probably less performant/efficient/discoverable).

My Idea would be to provide an `ofHoursMinutes()` (and maybe also `ofHours()`, `ofHoursMinutesSeconds()` and `ofTotalSeconds​()`) function [similar to Java](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/ZoneOffset.html#ofHoursMinutes(int,int)):
```kotlin
fun ofHoursMinutes(hours: Int, minutes: Int): ZoneOffset
```
and a parsing function that parses the time according to [RFC3339 `time-numoffset` or `time-offset`](https://tools.ietf.org/html/rfc3339#page-8) (like [Java's `of()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/ZoneOffset.html#of(java.lang.String))):
```kotlin
fun of(offsetId: String): ZoneOffset

ZoneOffset.of("+02:00")
ZoneOffset.of("Z")
```

A `ZoneOffset.UTC` would also be great.

This would greatly simplify #90.

_edited to adjust my ideas more towards what Java already does_

**Comment by cromefire** [comment]
It's also probably doable in common code, so implementing it once should be sufficient

**Comment by miguelhrocha** [comment]
Hey @cromefire do you still need someone to look into this? I can work on that this week

**Comment by cromefire** [comment]
Yes I still think that's a good addition, because I mean if you can't parse a zone offset into a ZoneOffset that doesn't seem very intuitive, right?

**Comment by miguelhrocha** [comment]
I think it makes total sense, it'll also help Java devs wanting to adopt the library. I'll work on it 👍

**Comment by dkhalanskyjb** [comment]
Adding a way to parse `ZoneOffset` would not be a big change—more or less all the required code is in place, we only need to make it public under some name—but we plan to change the role that `ZoneOffset` plays in our library. Until then, we intentionally keep the API surface of `ZoneOffset` slim.

As a side note, with the latest release, it is also possible to parse a `ZoneOffset` like this:
```kotlin
TimeZone.of("+02:00") as ZoneOffset
```

**Comment by ilya-g** [comment]
In the course of `ZoneOffset` refactoring (see #125) we're introducing a new `UtcOffset` class instead of `ZoneOffset` which can be constructed in various ways:
- parsed from an ISO string, e.g `+02:00`
- from total number of seconds: `UtcOffset(seconds = 1800)`
- from total number of minutes and number of seconds within a minute: `UtcOffset(minutes = 90, seconds = 0)`
- from hours, minutes, seconds components: `UtcOffset(hours = 3, minutes = 30)`
