### ISSUE TITLE
Bintray is having ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by lamba92** [Kotlin/kotlinx-datetime#98]
Please migrate as soon as possible to Maven Central, Bintray is shutting down! Or maybe to a stable public repo.

**Comment by jillesvangurp** [comment]
I tried building with jitpack.io but it seems the build file will need some changes to support that. I would appreciate some emergency fixes to fix that (or a move to maven central) for that so we can continue to depend on this library.
